// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common'

export declare namespace FareVaultV3 {
  export type FareVaultV3ParamsStruct = {
    fareTokenAddress: string
    evThreshold: BigNumberish
    vrfTimeout: BigNumberish
    networkFeeRecipientAddress: string
    minimumFeeBurnPercent: BigNumberish
    feeNetworkPercent: BigNumberish
    ethFarePrice: BigNumberish
    averageCallbackGas: BigNumberish
    vrfWrapperAddress: string
    keyHash: BytesLike
    subscriptionId: BigNumberish
    minimumRequestConfirmations: BigNumberish
    callbackGasLimit: BigNumberish
    vrfCoordinatorAddress: string
    useNativePayment: boolean
  }

  export type FareVaultV3ParamsStructOutput = [
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    string,
    string,
    BigNumber,
    number,
    number,
    string,
    boolean,
  ] & {
    fareTokenAddress: string
    evThreshold: BigNumber
    vrfTimeout: BigNumber
    networkFeeRecipientAddress: string
    minimumFeeBurnPercent: BigNumber
    feeNetworkPercent: BigNumber
    ethFarePrice: BigNumber
    averageCallbackGas: number
    vrfWrapperAddress: string
    keyHash: string
    subscriptionId: BigNumber
    minimumRequestConfirmations: number
    callbackGasLimit: number
    vrfCoordinatorAddress: string
    useNativePayment: boolean
  }

  export type ConfigParamsStruct = {
    ownerAddress: string
    fareTokenAddress: string
    evThreshold: BigNumberish
    vrfTimeout: BigNumberish
    networkFeeRecipientAddress: string
    minimumFeeBurnPercent: BigNumberish
    feeNetworkPercent: BigNumberish
    ethFarePrice: BigNumberish
    averageCallbackGas: BigNumberish
    vrfWrapperAddress: string
  }

  export type ConfigParamsStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    string,
  ] & {
    ownerAddress: string
    fareTokenAddress: string
    evThreshold: BigNumber
    vrfTimeout: BigNumber
    networkFeeRecipientAddress: string
    minimumFeeBurnPercent: BigNumber
    feeNetworkPercent: BigNumber
    ethFarePrice: BigNumber
    averageCallbackGas: number
    vrfWrapperAddress: string
  }

  export type QKWithConfigStruct = {
    q: BigNumberish[]
    k: BigNumberish[]
    feeLossMultiplier: BigNumberish
    feeMintMultiplier: BigNumberish
    effectiveEv: BigNumberish
  }

  export type QKWithConfigStructOutput = [
    BigNumber[],
    BigNumber[],
    BigNumber,
    BigNumber,
    BigNumber,
  ] & {
    q: BigNumber[]
    k: BigNumber[]
    feeLossMultiplier: BigNumber
    feeMintMultiplier: BigNumber
    effectiveEv: BigNumber
  }

  export type TrialStruct = {
    who: string
    timestamp: BigNumberish
    multiplier: BigNumberish
    qkWithConfigHash: BytesLike
    poolId: BigNumberish
    feeNetworkPercent: BigNumberish
  }

  export type TrialStructOutput = [string, BigNumber, BigNumber, string, BigNumber, BigNumber] & {
    who: string
    timestamp: BigNumber
    multiplier: BigNumber
    qkWithConfigHash: string
    poolId: BigNumber
    feeNetworkPercent: BigNumber
  }
}

export interface FareVaultV3Interface extends utils.Interface {
  functions: {
    'DEFAULT_ADMIN_ROLE()': FunctionFragment
    'PRECISE_UNIT()': FunctionFragment
    'RESOLVER_ROLE()': FunctionFragment
    'acceptOwnership()': FunctionFragment
    'averageCallbackGas()': FunctionFragment
    'callbackGasLimit()': FunctionFragment
    'configUpdate_averageCallbackGas(uint32)': FunctionFragment
    'configUpdate_ethFarePrice(uint256)': FunctionFragment
    'configUpdate_evThreshold(uint256)': FunctionFragment
    'configUpdate_feeNetworkPercent(uint256)': FunctionFragment
    'configUpdate_minimumFeeBurnPercent(uint256)': FunctionFragment
    'configUpdate_networkFeeRecipientAddress(address)': FunctionFragment
    'configUpdate_vrfWrapper(address)': FunctionFragment
    'configView()': FunctionFragment
    'ethFarePrice()': FunctionFragment
    'evThreshold()': FunctionFragment
    'extraordinaryResolve(uint256)': FunctionFragment
    'fareToken()': FunctionFragment
    'feeNetworkPercent()': FunctionFragment
    'getQKWithConfig(bytes32)': FunctionFragment
    'getQKWithConfigHash(uint256[],uint256[],uint256,uint256)': FunctionFragment
    'getRoleAdmin(bytes32)': FunctionFragment
    'getRoleMember(bytes32,uint256)': FunctionFragment
    'getRoleMemberCount(bytes32)': FunctionFragment
    'getRoleMembers(bytes32)': FunctionFragment
    'getTrialAndQKWithConfig(uint256)': FunctionFragment
    'grantRole(bytes32,address)': FunctionFragment
    'hasRole(bytes32,address)': FunctionFragment
    'keyHash()': FunctionFragment
    'minimumFeeBurnPercent()': FunctionFragment
    'minimumRequestConfirmations()': FunctionFragment
    'networkFeeRecipientAddress()': FunctionFragment
    'owner()': FunctionFragment
    'poolCount()': FunctionFragment
    'poolIdToPool(uint256)': FunctionFragment
    'poolRegister(address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)': FunctionFragment
    'poolUpdate_managerAddress(uint256,address)': FunctionFragment
    'qkWithConfigHashToQKWithConfig(bytes32)': FunctionFragment
    'qkWithConfigRegister(uint256[],uint256[],uint256,uint256)': FunctionFragment
    'rawFulfillRandomWords(uint256,uint256[])': FunctionFragment
    'renounceRole(bytes32,address)': FunctionFragment
    'revokeRole(bytes32,address)': FunctionFragment
    's_vrfCoordinator()': FunctionFragment
    'setCoordinator(address)': FunctionFragment
    'subscriptionId()': FunctionFragment
    'supportsInterface(bytes4)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'trialIdToTrial(uint256)': FunctionFragment
    'trialRegisterByQKWithConfig(uint256,uint256,uint256,uint256,uint256[],uint256[],bytes32)': FunctionFragment
    'trialRegisterByQKWithConfigHash(uint256,uint256,uint256,uint256,bytes32,bytes32)': FunctionFragment
    'uMAX_WHOLE_UD18x60()': FunctionFragment
    'useNativePayment()': FunctionFragment
    'vrfConfigUpdate(bytes32,uint256,uint16,uint32,bool)': FunctionFragment
    'vrfConfigView()': FunctionFragment
    'vrfTimeout()': FunctionFragment
    'vrfWrapper()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'DEFAULT_ADMIN_ROLE'
      | 'PRECISE_UNIT'
      | 'RESOLVER_ROLE'
      | 'acceptOwnership'
      | 'averageCallbackGas'
      | 'callbackGasLimit'
      | 'configUpdate_averageCallbackGas'
      | 'configUpdate_ethFarePrice'
      | 'configUpdate_evThreshold'
      | 'configUpdate_feeNetworkPercent'
      | 'configUpdate_minimumFeeBurnPercent'
      | 'configUpdate_networkFeeRecipientAddress'
      | 'configUpdate_vrfWrapper'
      | 'configView'
      | 'ethFarePrice'
      | 'evThreshold'
      | 'extraordinaryResolve'
      | 'fareToken'
      | 'feeNetworkPercent'
      | 'getQKWithConfig'
      | 'getQKWithConfigHash'
      | 'getRoleAdmin'
      | 'getRoleMember'
      | 'getRoleMemberCount'
      | 'getRoleMembers'
      | 'getTrialAndQKWithConfig'
      | 'grantRole'
      | 'hasRole'
      | 'keyHash'
      | 'minimumFeeBurnPercent'
      | 'minimumRequestConfirmations'
      | 'networkFeeRecipientAddress'
      | 'owner'
      | 'poolCount'
      | 'poolIdToPool'
      | 'poolRegister'
      | 'poolUpdate_managerAddress'
      | 'qkWithConfigHashToQKWithConfig'
      | 'qkWithConfigRegister'
      | 'rawFulfillRandomWords'
      | 'renounceRole'
      | 'revokeRole'
      | 's_vrfCoordinator'
      | 'setCoordinator'
      | 'subscriptionId'
      | 'supportsInterface'
      | 'transferOwnership'
      | 'trialIdToTrial'
      | 'trialRegisterByQKWithConfig'
      | 'trialRegisterByQKWithConfigHash'
      | 'uMAX_WHOLE_UD18x60'
      | 'useNativePayment'
      | 'vrfConfigUpdate'
      | 'vrfConfigView'
      | 'vrfTimeout'
      | 'vrfWrapper'
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string
  encodeFunctionData(functionFragment: 'PRECISE_UNIT', values?: undefined): string
  encodeFunctionData(functionFragment: 'RESOLVER_ROLE', values?: undefined): string
  encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string
  encodeFunctionData(functionFragment: 'averageCallbackGas', values?: undefined): string
  encodeFunctionData(functionFragment: 'callbackGasLimit', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'configUpdate_averageCallbackGas',
    values: [BigNumberish]
  ): string
  encodeFunctionData(functionFragment: 'configUpdate_ethFarePrice', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'configUpdate_evThreshold', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'configUpdate_feeNetworkPercent',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'configUpdate_minimumFeeBurnPercent',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'configUpdate_networkFeeRecipientAddress',
    values: [string]
  ): string
  encodeFunctionData(functionFragment: 'configUpdate_vrfWrapper', values: [string]): string
  encodeFunctionData(functionFragment: 'configView', values?: undefined): string
  encodeFunctionData(functionFragment: 'ethFarePrice', values?: undefined): string
  encodeFunctionData(functionFragment: 'evThreshold', values?: undefined): string
  encodeFunctionData(functionFragment: 'extraordinaryResolve', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'fareToken', values?: undefined): string
  encodeFunctionData(functionFragment: 'feeNetworkPercent', values?: undefined): string
  encodeFunctionData(functionFragment: 'getQKWithConfig', values: [BytesLike]): string
  encodeFunctionData(
    functionFragment: 'getQKWithConfigHash',
    values: [BigNumberish[], BigNumberish[], BigNumberish, BigNumberish]
  ): string
  encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getRoleMember', values: [BytesLike, BigNumberish]): string
  encodeFunctionData(functionFragment: 'getRoleMemberCount', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getRoleMembers', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getTrialAndQKWithConfig', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'keyHash', values?: undefined): string
  encodeFunctionData(functionFragment: 'minimumFeeBurnPercent', values?: undefined): string
  encodeFunctionData(functionFragment: 'minimumRequestConfirmations', values?: undefined): string
  encodeFunctionData(functionFragment: 'networkFeeRecipientAddress', values?: undefined): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(functionFragment: 'poolCount', values?: undefined): string
  encodeFunctionData(functionFragment: 'poolIdToPool', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'poolRegister',
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'poolUpdate_managerAddress',
    values: [BigNumberish, string]
  ): string
  encodeFunctionData(
    functionFragment: 'qkWithConfigHashToQKWithConfig',
    values: [BytesLike]
  ): string
  encodeFunctionData(
    functionFragment: 'qkWithConfigRegister',
    values: [BigNumberish[], BigNumberish[], BigNumberish, BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'rawFulfillRandomWords',
    values: [BigNumberish, BigNumberish[]]
  ): string
  encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 's_vrfCoordinator', values?: undefined): string
  encodeFunctionData(functionFragment: 'setCoordinator', values: [string]): string
  encodeFunctionData(functionFragment: 'subscriptionId', values?: undefined): string
  encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string
  encodeFunctionData(functionFragment: 'trialIdToTrial', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'trialRegisterByQKWithConfig',
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BigNumberish[],
      BytesLike,
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'trialRegisterByQKWithConfigHash',
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string
  encodeFunctionData(functionFragment: 'uMAX_WHOLE_UD18x60', values?: undefined): string
  encodeFunctionData(functionFragment: 'useNativePayment', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'vrfConfigUpdate',
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string
  encodeFunctionData(functionFragment: 'vrfConfigView', values?: undefined): string
  encodeFunctionData(functionFragment: 'vrfTimeout', values?: undefined): string
  encodeFunctionData(functionFragment: 'vrfWrapper', values?: undefined): string

  decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'PRECISE_UNIT', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'RESOLVER_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'averageCallbackGas', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'callbackGasLimit', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_averageCallbackGas', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_ethFarePrice', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_evThreshold', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_feeNetworkPercent', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'configUpdate_minimumFeeBurnPercent',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'configUpdate_networkFeeRecipientAddress',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'configUpdate_vrfWrapper', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configView', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'ethFarePrice', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'evThreshold', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'extraordinaryResolve', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'fareToken', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'feeNetworkPercent', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getQKWithConfig', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getQKWithConfigHash', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMember', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMemberCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMembers', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getTrialAndQKWithConfig', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'keyHash', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'minimumFeeBurnPercent', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'minimumRequestConfirmations', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'networkFeeRecipientAddress', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'poolCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'poolIdToPool', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'poolRegister', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'poolUpdate_managerAddress', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'qkWithConfigHashToQKWithConfig', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'qkWithConfigRegister', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rawFulfillRandomWords', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 's_vrfCoordinator', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setCoordinator', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'subscriptionId', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'trialIdToTrial', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'trialRegisterByQKWithConfig', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'trialRegisterByQKWithConfigHash', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'uMAX_WHOLE_UD18x60', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'useNativePayment', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vrfConfigUpdate', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vrfConfigView', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vrfTimeout', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vrfWrapper', data: BytesLike): Result

  events: {
    'AverageCallbackGasUpdated(uint32)': EventFragment
    'CoordinatorSet(address)': EventFragment
    'EthFarePriceUpdated(uint256)': EventFragment
    'EvThresholdUpdated(uint256)': EventFragment
    'FeeCharged(uint8,uint256,uint256,uint256)': EventFragment
    'FeeNetworkPercentUpdated(uint256)': EventFragment
    'MinimumFeeBurnPercentUpdated(uint256)': EventFragment
    'NetworkFeeRecipientAddressUpdated(address)': EventFragment
    'OwnershipTransferRequested(address,address)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
    'PoolAccumulatedAmountReleased(uint256,uint256,address,uint256)': EventFragment
    'PoolAccumulatedAmountUpdated(uint256,uint256,uint256)': EventFragment
    'PoolManagerUpdated(uint256,address)': EventFragment
    'PoolRegistered(uint256,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)': EventFragment
    'QKWithConfigRegistered(bytes32,uint256[],uint256[],uint256,uint256,uint256)': EventFragment
    'RoleAdminChanged(bytes32,bytes32,bytes32)': EventFragment
    'RoleGranted(bytes32,address,address)': EventFragment
    'RoleRevoked(bytes32,address,address)': EventFragment
    'TrialRegistered(uint256,address,uint256,uint256,bytes32,uint256,bytes32)': EventFragment
    'TrialResolved(uint256,uint256,uint256)': EventFragment
    'VRFConfigUpdated(bytes32,uint256,uint16,uint32,bool)': EventFragment
    'VRFWrapperUpdated(address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'AverageCallbackGasUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'CoordinatorSet'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'EthFarePriceUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'EvThresholdUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'FeeCharged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'FeeNetworkPercentUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'MinimumFeeBurnPercentUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'NetworkFeeRecipientAddressUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferRequested'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PoolAccumulatedAmountReleased'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PoolAccumulatedAmountUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PoolManagerUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PoolRegistered'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'QKWithConfigRegistered'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleAdminChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleGranted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleRevoked'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'TrialRegistered'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'TrialResolved'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'VRFConfigUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'VRFWrapperUpdated'): EventFragment
}

interface AverageCallbackGasUpdatedEventObject {
  newAverageCallbackGas: number
}

type AverageCallbackGasUpdatedEvent = TypedEvent<
  [number],
  AverageCallbackGasUpdatedEventObject
>

type AverageCallbackGasUpdatedEventFilter = TypedEventFilter<AverageCallbackGasUpdatedEvent>
interface CoordinatorSetEventObject {
  vrfCoordinator: string
}

type CoordinatorSetEvent = TypedEvent<[string], CoordinatorSetEventObject>

type CoordinatorSetEventFilter = TypedEventFilter<CoordinatorSetEvent>
interface EthFarePriceUpdatedEventObject {
  newEthFarePrice: BigNumber
}

type EthFarePriceUpdatedEvent = TypedEvent<[BigNumber], EthFarePriceUpdatedEventObject>

type EthFarePriceUpdatedEventFilter = TypedEventFilter<EthFarePriceUpdatedEvent>
interface EvThresholdUpdatedEventObject {
  newEvThreshold: BigNumber
}

type EvThresholdUpdatedEvent = TypedEvent<[BigNumber], EvThresholdUpdatedEventObject>

type EvThresholdUpdatedEventFilter = TypedEventFilter<EvThresholdUpdatedEvent>
interface FeeChargedEventObject {
  feeType: number
  poolId: BigNumber
  trialId: BigNumber
  feeAmount: BigNumber
}

type FeeChargedEvent = TypedEvent<
  [number, BigNumber, BigNumber, BigNumber],
  FeeChargedEventObject
>

type FeeChargedEventFilter = TypedEventFilter<FeeChargedEvent>

interface FeeNetworkPercentUpdatedEventObject {
  newFeeNetworkPercent: BigNumber
}

type FeeNetworkPercentUpdatedEvent = TypedEvent<
  [BigNumber],
  FeeNetworkPercentUpdatedEventObject
>

type FeeNetworkPercentUpdatedEventFilter = TypedEventFilter<FeeNetworkPercentUpdatedEvent>

 interface MinimumFeeBurnPercentUpdatedEventObject {
  newMinimumFeeBurnPercent: BigNumber
}

type MinimumFeeBurnPercentUpdatedEvent = TypedEvent<
  [BigNumber],
  MinimumFeeBurnPercentUpdatedEventObject
>

type MinimumFeeBurnPercentUpdatedEventFilter =
  TypedEventFilter<MinimumFeeBurnPercentUpdatedEvent>

interface NetworkFeeRecipientAddressUpdatedEventObject {
  newNetworkFeeRecipientAddress: string
}

type NetworkFeeRecipientAddressUpdatedEvent = TypedEvent<
  [string],
  NetworkFeeRecipientAddressUpdatedEventObject
>

type NetworkFeeRecipientAddressUpdatedEventFilter =
  TypedEventFilter<NetworkFeeRecipientAddressUpdatedEvent>
interface OwnershipTransferRequestedEventObject {
  from: string
  to: string
}

type OwnershipTransferRequestedEvent = TypedEvent<
  [string, string],
  OwnershipTransferRequestedEventObject
>

type OwnershipTransferRequestedEventFilter =
  TypedEventFilter<OwnershipTransferRequestedEvent>

interface OwnershipTransferredEventObject {
  from: string
  to: string
}

type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>

type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>
interface PoolAccumulatedAmountReleasedEventObject {
  poolId: BigNumber
  trialId: BigNumber
  receiver: string
  releasedAmount: BigNumber
}

type PoolAccumulatedAmountReleasedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber],
  PoolAccumulatedAmountReleasedEventObject
>

type PoolAccumulatedAmountReleasedEventFilter =
  TypedEventFilter<PoolAccumulatedAmountReleasedEvent>
interface PoolAccumulatedAmountUpdatedEventObject {
  poolId: BigNumber
  trialId: BigNumber
  newAccumulatedAmount: BigNumber
}

type PoolAccumulatedAmountUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  PoolAccumulatedAmountUpdatedEventObject
>

type PoolAccumulatedAmountUpdatedEventFilter =
  TypedEventFilter<PoolAccumulatedAmountUpdatedEvent>
interface PoolManagerUpdatedEventObject {
  poolId: BigNumber
  newPoolManager: string
}

type PoolManagerUpdatedEvent = TypedEvent<[BigNumber, string], PoolManagerUpdatedEventObject>

type PoolManagerUpdatedEventFilter = TypedEventFilter<PoolManagerUpdatedEvent>
interface PoolRegisteredEventObject {
  poolId: BigNumber
  managerAddress: string
  feePlayMultiplier: BigNumber
  feeLossMultiplier: BigNumber
  feeMintMultiplier: BigNumber
  feeHostPercent: BigNumber
  feePoolPercent: BigNumber
  minLimitForTicket: BigNumber
  probability: BigNumber
}

type PoolRegisteredEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  PoolRegisteredEventObject
>

type PoolRegisteredEventFilter = TypedEventFilter<PoolRegisteredEvent>

interface QKWithConfigRegisteredEventObject {
  qkWithConfigHash: string
  q: BigNumber[]
  k: BigNumber[]
  feeLossMultiplier: BigNumber
  feeMintMultiplier: BigNumber
  effectiveEv: BigNumber
}

type QKWithConfigRegisteredEvent = TypedEvent<
  [string, BigNumber[], BigNumber[], BigNumber, BigNumber, BigNumber],
  QKWithConfigRegisteredEventObject
>

type QKWithConfigRegisteredEventFilter = TypedEventFilter<QKWithConfigRegisteredEvent>
interface RoleAdminChangedEventObject {
  role: string
  previousAdminRole: string
  newAdminRole: string
}

type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>

type RoleAdminChangedEventFilter = TypedEventFilter<RoleAdminChangedEvent>
interface RoleGrantedEventObject {
  role: string
  account: string
  sender: string
}

type RoleGrantedEvent = TypedEvent<[string, string, string], RoleGrantedEventObject>

type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>
interface RoleRevokedEventObject {
  role: string
  account: string
  sender: string
}

type RoleRevokedEvent = TypedEvent<[string, string, string], RoleRevokedEventObject>

type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>
interface TrialRegisteredEventObject {
  trialId: BigNumber
  who: string
  poolId: BigNumber
  multiplier: BigNumber
  qkWithConfigHash: string
  vrfCostInFare: BigNumber
  extraDataHash: string
}

type TrialRegisteredEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string, BigNumber, string],
  TrialRegisteredEventObject
>

type TrialRegisteredEventFilter = TypedEventFilter<TrialRegisteredEvent>
interface TrialResolvedEventObject {
  trialId: BigNumber
  resultIndex: BigNumber
  randomness: BigNumber
}

type TrialResolvedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  TrialResolvedEventObject
>

type TrialResolvedEventFilter = TypedEventFilter<TrialResolvedEvent>
interface VRFConfigUpdatedEventObject {
  newKeyHash: string
  newSubscriptionId: BigNumber
  newMinimumRequestConfirmations: number
  newCallbackGasLimit: number
  newUseNativePayment: boolean
}

type VRFConfigUpdatedEvent = TypedEvent<
  [string, BigNumber, number, number, boolean],
  VRFConfigUpdatedEventObject
>

type VRFConfigUpdatedEventFilter = TypedEventFilter<VRFConfigUpdatedEvent>
interface VRFWrapperUpdatedEventObject {
  newVRFWrapperAddress: string
}

type VRFWrapperUpdatedEvent = TypedEvent<[string], VRFWrapperUpdatedEventObject>

type VRFWrapperUpdatedEventFilter = TypedEventFilter<VRFWrapperUpdatedEvent>

export interface FareVaultV3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: FareVaultV3Interface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>

    PRECISE_UNIT(overrides?: CallOverrides): Promise<[BigNumber]>

    RESOLVER_ROLE(overrides?: CallOverrides): Promise<[string]>

    acceptOwnership(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

    averageCallbackGas(overrides?: CallOverrides): Promise<[number]>

    callbackGasLimit(overrides?: CallOverrides): Promise<[number]>

    configUpdate_averageCallbackGas(
      _averageCallbackGas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_ethFarePrice(
      _ethFarePrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_evThreshold(
      _evThreshold: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_feeNetworkPercent(
      _feeNetworkPercent: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_minimumFeeBurnPercent(
      _minimumFeeBurnPercent: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_networkFeeRecipientAddress(
      _networkFeeRecipientAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_vrfWrapper(
      _vrfWrapperAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configView(overrides?: CallOverrides): Promise<[FareVaultV3.ConfigParamsStructOutput]>

    ethFarePrice(overrides?: CallOverrides): Promise<[BigNumber]>

    evThreshold(overrides?: CallOverrides): Promise<[BigNumber]>

    extraordinaryResolve(
      trialId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    fareToken(overrides?: CallOverrides): Promise<[string]>

    feeNetworkPercent(overrides?: CallOverrides): Promise<[BigNumber]>

    getQKWithConfig(
      qkWithConfigHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [FareVaultV3.QKWithConfigStructOutput] & {
        qkWithConfig: FareVaultV3.QKWithConfigStructOutput
      }
    >

    getQKWithConfigHash(
      q: BigNumberish[],
      k: BigNumberish[],
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>

    getRoleMembers(role: BytesLike, overrides?: CallOverrides): Promise<[string[]]>

    getTrialAndQKWithConfig(
      trialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[FareVaultV3.TrialStructOutput, FareVaultV3.QKWithConfigStructOutput]>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<[boolean]>

    keyHash(overrides?: CallOverrides): Promise<[string]>

    minimumFeeBurnPercent(overrides?: CallOverrides): Promise<[BigNumber]>

    minimumRequestConfirmations(overrides?: CallOverrides): Promise<[number]>

    networkFeeRecipientAddress(overrides?: CallOverrides): Promise<[string]>

    owner(overrides?: CallOverrides): Promise<[string]>

    poolCount(overrides?: CallOverrides): Promise<[BigNumber]>

    poolIdToPool(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
      ] & {
        managerAddress: string
        feePlayMultiplier: BigNumber
        feeLossMultiplier: BigNumber
        feeMintMultiplier: BigNumber
        feeHostPercent: BigNumber
        feePoolPercent: BigNumber
        minLimitForTicket: BigNumber
        probability: BigNumber
        accumulatedAmount: BigNumber
      }
    >

    poolRegister(
      managerAddress: string,
      feePlayMultiplier: BigNumberish,
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      feeHostPercent: BigNumberish,
      feePoolPercent: BigNumberish,
      minLimitForTicket: BigNumberish,
      probability: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    poolUpdate_managerAddress(
      poolId: BigNumberish,
      _managerAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    qkWithConfigHashToQKWithConfig(
      qkWithConfigHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        feeLossMultiplier: BigNumber
        feeMintMultiplier: BigNumber
        effectiveEv: BigNumber
      }
    >

    qkWithConfigRegister(
      q: BigNumberish[],
      k: BigNumberish[],
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    s_vrfCoordinator(overrides?: CallOverrides): Promise<[string]>

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    subscriptionId(overrides?: CallOverrides): Promise<[BigNumber]>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<[boolean]>

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    trialIdToTrial(
      trialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, BigNumber, BigNumber] & {
        who: string
        timestamp: BigNumber
        multiplier: BigNumber
        qkWithConfigHash: string
        poolId: BigNumber
        feeNetworkPercent: BigNumber
      }
    >

    trialRegisterByQKWithConfig(
      multiplier: BigNumberish,
      maxEthFarePrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      poolId: BigNumberish,
      q: BigNumberish[],
      k: BigNumberish[],
      extraDataHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    trialRegisterByQKWithConfigHash(
      multiplier: BigNumberish,
      maxEthFarePrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      poolId: BigNumberish,
      qkWithConfigHash: BytesLike,
      extraDataHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    uMAX_WHOLE_UD18x60(overrides?: CallOverrides): Promise<[BigNumber]>

    useNativePayment(overrides?: CallOverrides): Promise<[boolean]>

    vrfConfigUpdate(
      _keyHash: BytesLike,
      _subscriptionId: BigNumberish,
      _minimumRequestConfirmations: BigNumberish,
      _callbackGasLimit: BigNumberish,
      _useNativePayment: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    vrfConfigView(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, number, number, boolean]>

    vrfTimeout(overrides?: CallOverrides): Promise<[BigNumber]>

    vrfWrapper(overrides?: CallOverrides): Promise<[string]>
  }

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

  PRECISE_UNIT(overrides?: CallOverrides): Promise<BigNumber>

  RESOLVER_ROLE(overrides?: CallOverrides): Promise<string>

  acceptOwnership(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

  averageCallbackGas(overrides?: CallOverrides): Promise<number>

  callbackGasLimit(overrides?: CallOverrides): Promise<number>

  configUpdate_averageCallbackGas(
    _averageCallbackGas: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_ethFarePrice(
    _ethFarePrice: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_evThreshold(
    _evThreshold: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_feeNetworkPercent(
    _feeNetworkPercent: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_minimumFeeBurnPercent(
    _minimumFeeBurnPercent: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_networkFeeRecipientAddress(
    _networkFeeRecipientAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_vrfWrapper(
    _vrfWrapperAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configView(overrides?: CallOverrides): Promise<FareVaultV3.ConfigParamsStructOutput>

  ethFarePrice(overrides?: CallOverrides): Promise<BigNumber>

  evThreshold(overrides?: CallOverrides): Promise<BigNumber>

  extraordinaryResolve(
    trialId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  fareToken(overrides?: CallOverrides): Promise<string>

  feeNetworkPercent(overrides?: CallOverrides): Promise<BigNumber>

  getQKWithConfig(
    qkWithConfigHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<FareVaultV3.QKWithConfigStructOutput>

  getQKWithConfigHash(
    q: BigNumberish[],
    k: BigNumberish[],
    feeLossMultiplier: BigNumberish,
    feeMintMultiplier: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

  getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

  getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

  getRoleMembers(role: BytesLike, overrides?: CallOverrides): Promise<string[]>

  getTrialAndQKWithConfig(
    trialId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[FareVaultV3.TrialStructOutput, FareVaultV3.QKWithConfigStructOutput]>

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

  keyHash(overrides?: CallOverrides): Promise<string>

  minimumFeeBurnPercent(overrides?: CallOverrides): Promise<BigNumber>

  minimumRequestConfirmations(overrides?: CallOverrides): Promise<number>

  networkFeeRecipientAddress(overrides?: CallOverrides): Promise<string>

  owner(overrides?: CallOverrides): Promise<string>

  poolCount(overrides?: CallOverrides): Promise<BigNumber>

  poolIdToPool(
    poolId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
    ] & {
      managerAddress: string
      feePlayMultiplier: BigNumber
      feeLossMultiplier: BigNumber
      feeMintMultiplier: BigNumber
      feeHostPercent: BigNumber
      feePoolPercent: BigNumber
      minLimitForTicket: BigNumber
      probability: BigNumber
      accumulatedAmount: BigNumber
    }
  >

  poolRegister(
    managerAddress: string,
    feePlayMultiplier: BigNumberish,
    feeLossMultiplier: BigNumberish,
    feeMintMultiplier: BigNumberish,
    feeHostPercent: BigNumberish,
    feePoolPercent: BigNumberish,
    minLimitForTicket: BigNumberish,
    probability: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  poolUpdate_managerAddress(
    poolId: BigNumberish,
    _managerAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  qkWithConfigHashToQKWithConfig(
    qkWithConfigHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      feeLossMultiplier: BigNumber
      feeMintMultiplier: BigNumber
      effectiveEv: BigNumber
    }
  >

  qkWithConfigRegister(
    q: BigNumberish[],
    k: BigNumberish[],
    feeLossMultiplier: BigNumberish,
    feeMintMultiplier: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  rawFulfillRandomWords(
    requestId: BigNumberish,
    randomWords: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  renounceRole(
    role: BytesLike,
    callerConfirmation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  s_vrfCoordinator(overrides?: CallOverrides): Promise<string>

  setCoordinator(
    _vrfCoordinator: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  subscriptionId(overrides?: CallOverrides): Promise<BigNumber>

  supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

  transferOwnership(
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  trialIdToTrial(
    trialId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, string, BigNumber, BigNumber] & {
      who: string
      timestamp: BigNumber
      multiplier: BigNumber
      qkWithConfigHash: string
      poolId: BigNumber
      feeNetworkPercent: BigNumber
    }
  >

  trialRegisterByQKWithConfig(
    multiplier: BigNumberish,
    maxEthFarePrice: BigNumberish,
    maxAverageCallbackGas: BigNumberish,
    poolId: BigNumberish,
    q: BigNumberish[],
    k: BigNumberish[],
    extraDataHash: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  trialRegisterByQKWithConfigHash(
    multiplier: BigNumberish,
    maxEthFarePrice: BigNumberish,
    maxAverageCallbackGas: BigNumberish,
    poolId: BigNumberish,
    qkWithConfigHash: BytesLike,
    extraDataHash: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  uMAX_WHOLE_UD18x60(overrides?: CallOverrides): Promise<BigNumber>

  useNativePayment(overrides?: CallOverrides): Promise<boolean>

  vrfConfigUpdate(
    _keyHash: BytesLike,
    _subscriptionId: BigNumberish,
    _minimumRequestConfirmations: BigNumberish,
    _callbackGasLimit: BigNumberish,
    _useNativePayment: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  vrfConfigView(
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, number, number, boolean]>

  vrfTimeout(overrides?: CallOverrides): Promise<BigNumber>

  vrfWrapper(overrides?: CallOverrides): Promise<string>

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

    PRECISE_UNIT(overrides?: CallOverrides): Promise<BigNumber>

    RESOLVER_ROLE(overrides?: CallOverrides): Promise<string>

    acceptOwnership(overrides?: CallOverrides): Promise<void>

    averageCallbackGas(overrides?: CallOverrides): Promise<number>

    callbackGasLimit(overrides?: CallOverrides): Promise<number>

    configUpdate_averageCallbackGas(
      _averageCallbackGas: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    configUpdate_ethFarePrice(_ethFarePrice: BigNumberish, overrides?: CallOverrides): Promise<void>

    configUpdate_evThreshold(_evThreshold: BigNumberish, overrides?: CallOverrides): Promise<void>

    configUpdate_feeNetworkPercent(
      _feeNetworkPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    configUpdate_minimumFeeBurnPercent(
      _minimumFeeBurnPercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    configUpdate_networkFeeRecipientAddress(
      _networkFeeRecipientAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    configUpdate_vrfWrapper(_vrfWrapperAddress: string, overrides?: CallOverrides): Promise<void>

    configView(overrides?: CallOverrides): Promise<FareVaultV3.ConfigParamsStructOutput>

    ethFarePrice(overrides?: CallOverrides): Promise<BigNumber>

    evThreshold(overrides?: CallOverrides): Promise<BigNumber>

    extraordinaryResolve(trialId: BigNumberish, overrides?: CallOverrides): Promise<void>

    fareToken(overrides?: CallOverrides): Promise<string>

    feeNetworkPercent(overrides?: CallOverrides): Promise<BigNumber>

    getQKWithConfig(
      qkWithConfigHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<FareVaultV3.QKWithConfigStructOutput>

    getQKWithConfigHash(
      q: BigNumberish[],
      k: BigNumberish[],
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getRoleMembers(role: BytesLike, overrides?: CallOverrides): Promise<string[]>

    getTrialAndQKWithConfig(
      trialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[FareVaultV3.TrialStructOutput, FareVaultV3.QKWithConfigStructOutput]>

    grantRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

    keyHash(overrides?: CallOverrides): Promise<string>

    minimumFeeBurnPercent(overrides?: CallOverrides): Promise<BigNumber>

    minimumRequestConfirmations(overrides?: CallOverrides): Promise<number>

    networkFeeRecipientAddress(overrides?: CallOverrides): Promise<string>

    owner(overrides?: CallOverrides): Promise<string>

    poolCount(overrides?: CallOverrides): Promise<BigNumber>

    poolIdToPool(
      poolId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
      ] & {
        managerAddress: string
        feePlayMultiplier: BigNumber
        feeLossMultiplier: BigNumber
        feeMintMultiplier: BigNumber
        feeHostPercent: BigNumber
        feePoolPercent: BigNumber
        minLimitForTicket: BigNumber
        probability: BigNumber
        accumulatedAmount: BigNumber
      }
    >

    poolRegister(
      managerAddress: string,
      feePlayMultiplier: BigNumberish,
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      feeHostPercent: BigNumberish,
      feePoolPercent: BigNumberish,
      minLimitForTicket: BigNumberish,
      probability: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    poolUpdate_managerAddress(
      poolId: BigNumberish,
      _managerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    qkWithConfigHashToQKWithConfig(
      qkWithConfigHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        feeLossMultiplier: BigNumber
        feeMintMultiplier: BigNumber
        effectiveEv: BigNumber
      }
    >

    qkWithConfigRegister(
      q: BigNumberish[],
      k: BigNumberish[],
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: CallOverrides
    ): Promise<void>

    revokeRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    s_vrfCoordinator(overrides?: CallOverrides): Promise<string>

    setCoordinator(_vrfCoordinator: string, overrides?: CallOverrides): Promise<void>

    subscriptionId(overrides?: CallOverrides): Promise<BigNumber>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

    transferOwnership(to: string, overrides?: CallOverrides): Promise<void>

    trialIdToTrial(
      trialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, BigNumber, BigNumber] & {
        who: string
        timestamp: BigNumber
        multiplier: BigNumber
        qkWithConfigHash: string
        poolId: BigNumber
        feeNetworkPercent: BigNumber
      }
    >

    trialRegisterByQKWithConfig(
      multiplier: BigNumberish,
      maxEthFarePrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      poolId: BigNumberish,
      q: BigNumberish[],
      k: BigNumberish[],
      extraDataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    trialRegisterByQKWithConfigHash(
      multiplier: BigNumberish,
      maxEthFarePrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      poolId: BigNumberish,
      qkWithConfigHash: BytesLike,
      extraDataHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    uMAX_WHOLE_UD18x60(overrides?: CallOverrides): Promise<BigNumber>

    useNativePayment(overrides?: CallOverrides): Promise<boolean>

    vrfConfigUpdate(
      _keyHash: BytesLike,
      _subscriptionId: BigNumberish,
      _minimumRequestConfirmations: BigNumberish,
      _callbackGasLimit: BigNumberish,
      _useNativePayment: boolean,
      overrides?: CallOverrides
    ): Promise<void>

    vrfConfigView(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, number, number, boolean]>

    vrfTimeout(overrides?: CallOverrides): Promise<BigNumber>

    vrfWrapper(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    'AverageCallbackGasUpdated(uint32)'(
      newAverageCallbackGas?: null
    ): AverageCallbackGasUpdatedEventFilter
    AverageCallbackGasUpdated(newAverageCallbackGas?: null): AverageCallbackGasUpdatedEventFilter

    'CoordinatorSet(address)'(vrfCoordinator?: null): CoordinatorSetEventFilter
    CoordinatorSet(vrfCoordinator?: null): CoordinatorSetEventFilter

    'EthFarePriceUpdated(uint256)'(newEthFarePrice?: null): EthFarePriceUpdatedEventFilter
    EthFarePriceUpdated(newEthFarePrice?: null): EthFarePriceUpdatedEventFilter

    'EvThresholdUpdated(uint256)'(newEvThreshold?: null): EvThresholdUpdatedEventFilter
    EvThresholdUpdated(newEvThreshold?: null): EvThresholdUpdatedEventFilter

    'FeeCharged(uint8,uint256,uint256,uint256)'(
      feeType?: BigNumberish | null,
      poolId?: BigNumberish | null,
      trialId?: BigNumberish | null,
      feeAmount?: null
    ): FeeChargedEventFilter
    FeeCharged(
      feeType?: BigNumberish | null,
      poolId?: BigNumberish | null,
      trialId?: BigNumberish | null,
      feeAmount?: null
    ): FeeChargedEventFilter

    'FeeNetworkPercentUpdated(uint256)'(
      newFeeNetworkPercent?: null
    ): FeeNetworkPercentUpdatedEventFilter
    FeeNetworkPercentUpdated(newFeeNetworkPercent?: null): FeeNetworkPercentUpdatedEventFilter

    'MinimumFeeBurnPercentUpdated(uint256)'(
      newMinimumFeeBurnPercent?: null
    ): MinimumFeeBurnPercentUpdatedEventFilter
    MinimumFeeBurnPercentUpdated(
      newMinimumFeeBurnPercent?: null
    ): MinimumFeeBurnPercentUpdatedEventFilter

    'NetworkFeeRecipientAddressUpdated(address)'(
      newNetworkFeeRecipientAddress?: null
    ): NetworkFeeRecipientAddressUpdatedEventFilter
    NetworkFeeRecipientAddressUpdated(
      newNetworkFeeRecipientAddress?: null
    ): NetworkFeeRecipientAddressUpdatedEventFilter

    'OwnershipTransferRequested(address,address)'(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferRequestedEventFilter
    OwnershipTransferRequested(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferRequestedEventFilter

    'OwnershipTransferred(address,address)'(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(from?: string | null, to?: string | null): OwnershipTransferredEventFilter

    'PoolAccumulatedAmountReleased(uint256,uint256,address,uint256)'(
      poolId?: BigNumberish | null,
      trialId?: BigNumberish | null,
      receiver?: string | null,
      releasedAmount?: null
    ): PoolAccumulatedAmountReleasedEventFilter
    PoolAccumulatedAmountReleased(
      poolId?: BigNumberish | null,
      trialId?: BigNumberish | null,
      receiver?: string | null,
      releasedAmount?: null
    ): PoolAccumulatedAmountReleasedEventFilter

    'PoolAccumulatedAmountUpdated(uint256,uint256,uint256)'(
      poolId?: BigNumberish | null,
      trialId?: BigNumberish | null,
      newAccumulatedAmount?: null
    ): PoolAccumulatedAmountUpdatedEventFilter
    PoolAccumulatedAmountUpdated(
      poolId?: BigNumberish | null,
      trialId?: BigNumberish | null,
      newAccumulatedAmount?: null
    ): PoolAccumulatedAmountUpdatedEventFilter

    'PoolManagerUpdated(uint256,address)'(
      poolId?: BigNumberish | null,
      newPoolManager?: string | null
    ): PoolManagerUpdatedEventFilter
    PoolManagerUpdated(
      poolId?: BigNumberish | null,
      newPoolManager?: string | null
    ): PoolManagerUpdatedEventFilter

    'PoolRegistered(uint256,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256)'(
      poolId?: BigNumberish | null,
      managerAddress?: string | null,
      feePlayMultiplier?: null,
      feeLossMultiplier?: null,
      feeMintMultiplier?: null,
      feeHostPercent?: null,
      feePoolPercent?: null,
      minLimitForTicket?: null,
      probability?: null
    ): PoolRegisteredEventFilter
    PoolRegistered(
      poolId?: BigNumberish | null,
      managerAddress?: string | null,
      feePlayMultiplier?: null,
      feeLossMultiplier?: null,
      feeMintMultiplier?: null,
      feeHostPercent?: null,
      feePoolPercent?: null,
      minLimitForTicket?: null,
      probability?: null
    ): PoolRegisteredEventFilter

    'QKWithConfigRegistered(bytes32,uint256[],uint256[],uint256,uint256,uint256)'(
      qkWithConfigHash?: BytesLike | null,
      q?: null,
      k?: null,
      feeLossMultiplier?: null,
      feeMintMultiplier?: null,
      effectiveEv?: null
    ): QKWithConfigRegisteredEventFilter
    QKWithConfigRegistered(
      qkWithConfigHash?: BytesLike | null,
      q?: null,
      k?: null,
      feeLossMultiplier?: null,
      feeMintMultiplier?: null,
      effectiveEv?: null
    ): QKWithConfigRegisteredEventFilter

    'RoleAdminChanged(bytes32,bytes32,bytes32)'(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter

    'RoleGranted(bytes32,address,address)'(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter

    'RoleRevoked(bytes32,address,address)'(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter

    'TrialRegistered(uint256,address,uint256,uint256,bytes32,uint256,bytes32)'(
      trialId?: BigNumberish | null,
      who?: string | null,
      poolId?: BigNumberish | null,
      multiplier?: null,
      qkWithConfigHash?: null,
      vrfCostInFare?: null,
      extraDataHash?: null
    ): TrialRegisteredEventFilter
    TrialRegistered(
      trialId?: BigNumberish | null,
      who?: string | null,
      poolId?: BigNumberish | null,
      multiplier?: null,
      qkWithConfigHash?: null,
      vrfCostInFare?: null,
      extraDataHash?: null
    ): TrialRegisteredEventFilter

    'TrialResolved(uint256,uint256,uint256)'(
      trialId?: BigNumberish | null,
      resultIndex?: null,
      randomness?: null
    ): TrialResolvedEventFilter
    TrialResolved(
      trialId?: BigNumberish | null,
      resultIndex?: null,
      randomness?: null
    ): TrialResolvedEventFilter

    'VRFConfigUpdated(bytes32,uint256,uint16,uint32,bool)'(
      newKeyHash?: null,
      newSubscriptionId?: null,
      newMinimumRequestConfirmations?: null,
      newCallbackGasLimit?: null,
      newUseNativePayment?: null
    ): VRFConfigUpdatedEventFilter
    VRFConfigUpdated(
      newKeyHash?: null,
      newSubscriptionId?: null,
      newMinimumRequestConfirmations?: null,
      newCallbackGasLimit?: null,
      newUseNativePayment?: null
    ): VRFConfigUpdatedEventFilter

    'VRFWrapperUpdated(address)'(newVRFWrapperAddress?: null): VRFWrapperUpdatedEventFilter
    VRFWrapperUpdated(newVRFWrapperAddress?: null): VRFWrapperUpdatedEventFilter
  }

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    PRECISE_UNIT(overrides?: CallOverrides): Promise<BigNumber>

    RESOLVER_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    acceptOwnership(overrides?: Overrides & { from?: string }): Promise<BigNumber>

    averageCallbackGas(overrides?: CallOverrides): Promise<BigNumber>

    callbackGasLimit(overrides?: CallOverrides): Promise<BigNumber>

    configUpdate_averageCallbackGas(
      _averageCallbackGas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_ethFarePrice(
      _ethFarePrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_evThreshold(
      _evThreshold: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_feeNetworkPercent(
      _feeNetworkPercent: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_minimumFeeBurnPercent(
      _minimumFeeBurnPercent: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_networkFeeRecipientAddress(
      _networkFeeRecipientAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_vrfWrapper(
      _vrfWrapperAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configView(overrides?: CallOverrides): Promise<BigNumber>

    ethFarePrice(overrides?: CallOverrides): Promise<BigNumber>

    evThreshold(overrides?: CallOverrides): Promise<BigNumber>

    extraordinaryResolve(
      trialId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    fareToken(overrides?: CallOverrides): Promise<BigNumber>

    feeNetworkPercent(overrides?: CallOverrides): Promise<BigNumber>

    getQKWithConfig(qkWithConfigHash: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getQKWithConfigHash(
      q: BigNumberish[],
      k: BigNumberish[],
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getRoleMembers(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getTrialAndQKWithConfig(trialId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<BigNumber>

    keyHash(overrides?: CallOverrides): Promise<BigNumber>

    minimumFeeBurnPercent(overrides?: CallOverrides): Promise<BigNumber>

    minimumRequestConfirmations(overrides?: CallOverrides): Promise<BigNumber>

    networkFeeRecipientAddress(overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    poolCount(overrides?: CallOverrides): Promise<BigNumber>

    poolIdToPool(poolId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    poolRegister(
      managerAddress: string,
      feePlayMultiplier: BigNumberish,
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      feeHostPercent: BigNumberish,
      feePoolPercent: BigNumberish,
      minLimitForTicket: BigNumberish,
      probability: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    poolUpdate_managerAddress(
      poolId: BigNumberish,
      _managerAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    qkWithConfigHashToQKWithConfig(
      qkWithConfigHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    qkWithConfigRegister(
      q: BigNumberish[],
      k: BigNumberish[],
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    s_vrfCoordinator(overrides?: CallOverrides): Promise<BigNumber>

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    subscriptionId(overrides?: CallOverrides): Promise<BigNumber>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    transferOwnership(to: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>

    trialIdToTrial(trialId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    trialRegisterByQKWithConfig(
      multiplier: BigNumberish,
      maxEthFarePrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      poolId: BigNumberish,
      q: BigNumberish[],
      k: BigNumberish[],
      extraDataHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    trialRegisterByQKWithConfigHash(
      multiplier: BigNumberish,
      maxEthFarePrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      poolId: BigNumberish,
      qkWithConfigHash: BytesLike,
      extraDataHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    uMAX_WHOLE_UD18x60(overrides?: CallOverrides): Promise<BigNumber>

    useNativePayment(overrides?: CallOverrides): Promise<BigNumber>

    vrfConfigUpdate(
      _keyHash: BytesLike,
      _subscriptionId: BigNumberish,
      _minimumRequestConfirmations: BigNumberish,
      _callbackGasLimit: BigNumberish,
      _useNativePayment: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    vrfConfigView(overrides?: CallOverrides): Promise<BigNumber>

    vrfTimeout(overrides?: CallOverrides): Promise<BigNumber>

    vrfWrapper(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    PRECISE_UNIT(overrides?: CallOverrides): Promise<PopulatedTransaction>

    RESOLVER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    acceptOwnership(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>

    averageCallbackGas(overrides?: CallOverrides): Promise<PopulatedTransaction>

    callbackGasLimit(overrides?: CallOverrides): Promise<PopulatedTransaction>

    configUpdate_averageCallbackGas(
      _averageCallbackGas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_ethFarePrice(
      _ethFarePrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_evThreshold(
      _evThreshold: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_feeNetworkPercent(
      _feeNetworkPercent: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_minimumFeeBurnPercent(
      _minimumFeeBurnPercent: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_networkFeeRecipientAddress(
      _networkFeeRecipientAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_vrfWrapper(
      _vrfWrapperAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configView(overrides?: CallOverrides): Promise<PopulatedTransaction>

    ethFarePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>

    evThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>

    extraordinaryResolve(
      trialId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    fareToken(overrides?: CallOverrides): Promise<PopulatedTransaction>

    feeNetworkPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getQKWithConfig(
      qkWithConfigHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getQKWithConfigHash(
      q: BigNumberish[],
      k: BigNumberish[],
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getRoleMembers(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getTrialAndQKWithConfig(
      trialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    keyHash(overrides?: CallOverrides): Promise<PopulatedTransaction>

    minimumFeeBurnPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>

    minimumRequestConfirmations(overrides?: CallOverrides): Promise<PopulatedTransaction>

    networkFeeRecipientAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    poolCount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    poolIdToPool(poolId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    poolRegister(
      managerAddress: string,
      feePlayMultiplier: BigNumberish,
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      feeHostPercent: BigNumberish,
      feePoolPercent: BigNumberish,
      minLimitForTicket: BigNumberish,
      probability: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    poolUpdate_managerAddress(
      poolId: BigNumberish,
      _managerAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    qkWithConfigHashToQKWithConfig(
      qkWithConfigHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    qkWithConfigRegister(
      q: BigNumberish[],
      k: BigNumberish[],
      feeLossMultiplier: BigNumberish,
      feeMintMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    s_vrfCoordinator(overrides?: CallOverrides): Promise<PopulatedTransaction>

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    subscriptionId(overrides?: CallOverrides): Promise<PopulatedTransaction>

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    trialIdToTrial(trialId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    trialRegisterByQKWithConfig(
      multiplier: BigNumberish,
      maxEthFarePrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      poolId: BigNumberish,
      q: BigNumberish[],
      k: BigNumberish[],
      extraDataHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    trialRegisterByQKWithConfigHash(
      multiplier: BigNumberish,
      maxEthFarePrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      poolId: BigNumberish,
      qkWithConfigHash: BytesLike,
      extraDataHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    uMAX_WHOLE_UD18x60(overrides?: CallOverrides): Promise<PopulatedTransaction>

    useNativePayment(overrides?: CallOverrides): Promise<PopulatedTransaction>

    vrfConfigUpdate(
      _keyHash: BytesLike,
      _subscriptionId: BigNumberish,
      _minimumRequestConfirmations: BigNumberish,
      _callbackGasLimit: BigNumberish,
      _useNativePayment: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    vrfConfigView(overrides?: CallOverrides): Promise<PopulatedTransaction>

    vrfTimeout(overrides?: CallOverrides): Promise<PopulatedTransaction>

    vrfWrapper(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
