// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common'

export interface FareAAInterface extends utils.Interface {
  functions: {
    'DEFAULT_ADMIN_ROLE()': FunctionFragment
    'MINTER_ROLE()': FunctionFragment
    'batchChargeTrialAndFeeUsdc(address,address,uint256,uint256,address)': FunctionFragment
    'chargeFeeUsdc(address,address,uint256,address)': FunctionFragment
    'chargeTrialUsdc(address,address,uint256)': FunctionFragment
    'fundOwnerAddressToContractAddressToIsAllowed(address,address)': FunctionFragment
    'fundOwnerAddressToSubmitterAddressToIsAllowed(address,address)': FunctionFragment
    'getRoleAdmin(bytes32)': FunctionFragment
    'getRoleMember(bytes32,uint256)': FunctionFragment
    'getRoleMemberCount(bytes32)': FunctionFragment
    'grantRole(bytes32,address)': FunctionFragment
    'hasRole(bytes32,address)': FunctionFragment
    'isMinterContract(address)': FunctionFragment
    'isProfitValid(uint256)': FunctionFragment
    'isValidContractForFundOwner(address,address)': FunctionFragment
    'isValidSubmitterForFundOwner(address,address)': FunctionFragment
    'payoutUsdc(address,uint256)': FunctionFragment
    'renounceRole(bytes32,address)': FunctionFragment
    'revokeRole(bytes32,address)': FunctionFragment
    'riskFactor()': FunctionFragment
    'setAllowedContracts(address[],bool[])': FunctionFragment
    'setAllowedSubmitter(address,bool)': FunctionFragment
    'setRiskFactor(uint256)': FunctionFragment
    'supportsInterface(bytes4)': FunctionFragment
    'usdc()': FunctionFragment
    'usdcAddress()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'DEFAULT_ADMIN_ROLE'
      | 'MINTER_ROLE'
      | 'batchChargeTrialAndFeeUsdc'
      | 'chargeFeeUsdc'
      | 'chargeTrialUsdc'
      | 'fundOwnerAddressToContractAddressToIsAllowed'
      | 'fundOwnerAddressToSubmitterAddressToIsAllowed'
      | 'getRoleAdmin'
      | 'getRoleMember'
      | 'getRoleMemberCount'
      | 'grantRole'
      | 'hasRole'
      | 'isMinterContract'
      | 'isProfitValid'
      | 'isValidContractForFundOwner'
      | 'isValidSubmitterForFundOwner'
      | 'payoutUsdc'
      | 'renounceRole'
      | 'revokeRole'
      | 'riskFactor'
      | 'setAllowedContracts'
      | 'setAllowedSubmitter'
      | 'setRiskFactor'
      | 'supportsInterface'
      | 'usdc'
      | 'usdcAddress'
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string
  encodeFunctionData(functionFragment: 'MINTER_ROLE', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'batchChargeTrialAndFeeUsdc',
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string
  encodeFunctionData(
    functionFragment: 'chargeFeeUsdc',
    values: [string, string, BigNumberish, string]
  ): string
  encodeFunctionData(
    functionFragment: 'chargeTrialUsdc',
    values: [string, string, BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'fundOwnerAddressToContractAddressToIsAllowed',
    values: [string, string]
  ): string
  encodeFunctionData(
    functionFragment: 'fundOwnerAddressToSubmitterAddressToIsAllowed',
    values: [string, string]
  ): string
  encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getRoleMember', values: [BytesLike, BigNumberish]): string
  encodeFunctionData(functionFragment: 'getRoleMemberCount', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'isMinterContract', values: [string]): string
  encodeFunctionData(functionFragment: 'isProfitValid', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'isValidContractForFundOwner',
    values: [string, string]
  ): string
  encodeFunctionData(
    functionFragment: 'isValidSubmitterForFundOwner',
    values: [string, string]
  ): string
  encodeFunctionData(functionFragment: 'payoutUsdc', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'riskFactor', values?: undefined): string
  encodeFunctionData(functionFragment: 'setAllowedContracts', values: [string[], boolean[]]): string
  encodeFunctionData(functionFragment: 'setAllowedSubmitter', values: [string, boolean]): string
  encodeFunctionData(functionFragment: 'setRiskFactor', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'usdc', values?: undefined): string
  encodeFunctionData(functionFragment: 'usdcAddress', values?: undefined): string

  decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'MINTER_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'batchChargeTrialAndFeeUsdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'chargeFeeUsdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'chargeTrialUsdc', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'fundOwnerAddressToContractAddressToIsAllowed',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'fundOwnerAddressToSubmitterAddressToIsAllowed',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMember', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMemberCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isMinterContract', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isProfitValid', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isValidContractForFundOwner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isValidSubmitterForFundOwner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'payoutUsdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'riskFactor', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setAllowedContracts', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setAllowedSubmitter', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setRiskFactor', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'usdcAddress', data: BytesLike): Result

  events: {
    'AllowedContractsSet(address,address[],bool[])': EventFragment
    'AllowedSubmitterSet(address,address,bool)': EventFragment
    'RiskFactorSet(uint256)': EventFragment
    'RoleAdminChanged(bytes32,bytes32,bytes32)': EventFragment
    'RoleGranted(bytes32,address,address)': EventFragment
    'RoleRevoked(bytes32,address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'AllowedContractsSet'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'AllowedSubmitterSet'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RiskFactorSet'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleAdminChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleGranted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleRevoked'): EventFragment
}

interface AllowedContractsSetEventObject {
  fundOwnerAddress: string
  contractAddresses: string[]
  isAlloweds: boolean[]
}
type AllowedContractsSetEvent = TypedEvent<
  [string, string[], boolean[]],
  AllowedContractsSetEventObject
>

type AllowedContractsSetEventFilter = TypedEventFilter<AllowedContractsSetEvent>

interface AllowedSubmitterSetEventObject {
  fundOwnerAddress: string
  submitterAddress: string
  isAllowed: boolean
}

type AllowedSubmitterSetEvent = TypedEvent<
  [string, string, boolean],
  AllowedSubmitterSetEventObject
>

type AllowedSubmitterSetEventFilter = TypedEventFilter<AllowedSubmitterSetEvent>

interface RiskFactorSetEventObject {
  newRiskFactor: BigNumber
}

type RiskFactorSetEvent = TypedEvent<[BigNumber], RiskFactorSetEventObject>

type RiskFactorSetEventFilter = TypedEventFilter<RiskFactorSetEvent>
interface RoleAdminChangedEventObject {
  role: string
  previousAdminRole: string
  newAdminRole: string
}

type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>

type RoleAdminChangedEventFilter = TypedEventFilter<RoleAdminChangedEvent>

interface RoleGrantedEventObject {
  role: string
  account: string
  sender: string
}

type RoleGrantedEvent = TypedEvent<[string, string, string], RoleGrantedEventObject>

type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>
interface RoleRevokedEventObject {
  role: string
  account: string
  sender: string
}

type RoleRevokedEvent = TypedEvent<[string, string, string], RoleRevokedEventObject>

type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>

export interface FareAA extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: FareAAInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>

    MINTER_ROLE(overrides?: CallOverrides): Promise<[string]>

    batchChargeTrialAndFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      trialAmount: BigNumberish,
      feeAmount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    chargeFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    chargeTrialUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    fundOwnerAddressToContractAddressToIsAllowed(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    fundOwnerAddressToSubmitterAddressToIsAllowed(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<[boolean]>

    isMinterContract(contractAddress: string, overrides?: CallOverrides): Promise<[boolean]>

    isProfitValid(
      potentialProfitAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    isValidContractForFundOwner(
      contractAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    isValidSubmitterForFundOwner(
      submitterAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    payoutUsdc(
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    riskFactor(overrides?: CallOverrides): Promise<[BigNumber]>

    setAllowedContracts(
      contractAddresses: string[],
      isAlloweds: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    setAllowedSubmitter(
      submitterAddress: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    setRiskFactor(
      _riskFactor: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<[boolean]>

    usdc(overrides?: CallOverrides): Promise<[string]>

    usdcAddress(overrides?: CallOverrides): Promise<[string]>
  }

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

  MINTER_ROLE(overrides?: CallOverrides): Promise<string>

  batchChargeTrialAndFeeUsdc(
    submitterAddress: string,
    fundOwnerAddress: string,
    trialAmount: BigNumberish,
    feeAmount: BigNumberish,
    receiverAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  chargeFeeUsdc(
    submitterAddress: string,
    fundOwnerAddress: string,
    amount: BigNumberish,
    receiverAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  chargeTrialUsdc(
    submitterAddress: string,
    fundOwnerAddress: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  fundOwnerAddressToContractAddressToIsAllowed(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  fundOwnerAddressToSubmitterAddressToIsAllowed(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

  getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

  getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

  isMinterContract(contractAddress: string, overrides?: CallOverrides): Promise<boolean>

  isProfitValid(potentialProfitAmount: BigNumberish, overrides?: CallOverrides): Promise<boolean>

  isValidContractForFundOwner(
    contractAddress: string,
    fundOwnerAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  isValidSubmitterForFundOwner(
    submitterAddress: string,
    fundOwnerAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  payoutUsdc(
    fundOwnerAddress: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  renounceRole(
    role: BytesLike,
    callerConfirmation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  riskFactor(overrides?: CallOverrides): Promise<BigNumber>

  setAllowedContracts(
    contractAddresses: string[],
    isAlloweds: boolean[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  setAllowedSubmitter(
    submitterAddress: string,
    isAllowed: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  setRiskFactor(
    _riskFactor: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

  usdc(overrides?: CallOverrides): Promise<string>

  usdcAddress(overrides?: CallOverrides): Promise<string>

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

    MINTER_ROLE(overrides?: CallOverrides): Promise<string>

    batchChargeTrialAndFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      trialAmount: BigNumberish,
      feeAmount: BigNumberish,
      receiverAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    chargeFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      receiverAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    chargeTrialUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    fundOwnerAddressToContractAddressToIsAllowed(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    fundOwnerAddressToSubmitterAddressToIsAllowed(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    grantRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

    isMinterContract(contractAddress: string, overrides?: CallOverrides): Promise<boolean>

    isProfitValid(potentialProfitAmount: BigNumberish, overrides?: CallOverrides): Promise<boolean>

    isValidContractForFundOwner(
      contractAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    isValidSubmitterForFundOwner(
      submitterAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    payoutUsdc(
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: CallOverrides
    ): Promise<void>

    revokeRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    riskFactor(overrides?: CallOverrides): Promise<BigNumber>

    setAllowedContracts(
      contractAddresses: string[],
      isAlloweds: boolean[],
      overrides?: CallOverrides
    ): Promise<void>

    setAllowedSubmitter(
      submitterAddress: string,
      isAllowed: boolean,
      overrides?: CallOverrides
    ): Promise<void>

    setRiskFactor(_riskFactor: BigNumberish, overrides?: CallOverrides): Promise<void>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

    usdc(overrides?: CallOverrides): Promise<string>

    usdcAddress(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    'AllowedContractsSet(address,address[],bool[])'(
      fundOwnerAddress?: string | null,
      contractAddresses?: string[] | null,
      isAlloweds?: null
    ): AllowedContractsSetEventFilter
    AllowedContractsSet(
      fundOwnerAddress?: string | null,
      contractAddresses?: string[] | null,
      isAlloweds?: null
    ): AllowedContractsSetEventFilter

    'AllowedSubmitterSet(address,address,bool)'(
      fundOwnerAddress?: string | null,
      submitterAddress?: string | null,
      isAllowed?: null
    ): AllowedSubmitterSetEventFilter
    AllowedSubmitterSet(
      fundOwnerAddress?: string | null,
      submitterAddress?: string | null,
      isAllowed?: null
    ): AllowedSubmitterSetEventFilter

    'RiskFactorSet(uint256)'(newRiskFactor?: null): RiskFactorSetEventFilter
    RiskFactorSet(newRiskFactor?: null): RiskFactorSetEventFilter

    'RoleAdminChanged(bytes32,bytes32,bytes32)'(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter

    'RoleGranted(bytes32,address,address)'(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter

    'RoleRevoked(bytes32,address,address)'(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter
  }

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    MINTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    batchChargeTrialAndFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      trialAmount: BigNumberish,
      feeAmount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    chargeFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    chargeTrialUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    fundOwnerAddressToContractAddressToIsAllowed(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    fundOwnerAddressToSubmitterAddressToIsAllowed(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<BigNumber>

    isMinterContract(contractAddress: string, overrides?: CallOverrides): Promise<BigNumber>

    isProfitValid(
      potentialProfitAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    isValidContractForFundOwner(
      contractAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    isValidSubmitterForFundOwner(
      submitterAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    payoutUsdc(
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    riskFactor(overrides?: CallOverrides): Promise<BigNumber>

    setAllowedContracts(
      contractAddresses: string[],
      isAlloweds: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    setAllowedSubmitter(
      submitterAddress: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    setRiskFactor(
      _riskFactor: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    usdc(overrides?: CallOverrides): Promise<BigNumber>

    usdcAddress(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    MINTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    batchChargeTrialAndFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      trialAmount: BigNumberish,
      feeAmount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    chargeFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    chargeTrialUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    fundOwnerAddressToContractAddressToIsAllowed(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    fundOwnerAddressToSubmitterAddressToIsAllowed(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isMinterContract(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isProfitValid(
      potentialProfitAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isValidContractForFundOwner(
      contractAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isValidSubmitterForFundOwner(
      submitterAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    payoutUsdc(
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    riskFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>

    setAllowedContracts(
      contractAddresses: string[],
      isAlloweds: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    setAllowedSubmitter(
      submitterAddress: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    setRiskFactor(
      _riskFactor: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>

    usdcAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
