// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common'

export interface IFareAAInterface extends utils.Interface {
  functions: {
    'MINTER_ROLE()': FunctionFragment
    'batchChargeTrialAndFeeUsdc(address,address,uint256,uint256,address)': FunctionFragment
    'chargeFeeUsdc(address,address,uint256,address)': FunctionFragment
    'chargeTrialUsdc(address,address,uint256)': FunctionFragment
    'isMinterContract(address)': FunctionFragment
    'isProfitValid(uint256)': FunctionFragment
    'isValidContractForFundOwner(address,address)': FunctionFragment
    'isValidSubmitterForFundOwner(address,address)': FunctionFragment
    'payoutUsdc(address,uint256)': FunctionFragment
    'riskFactor()': FunctionFragment
    'setAllowedContracts(address[],bool[])': FunctionFragment
    'setAllowedSubmitter(address,bool)': FunctionFragment
    'setRiskFactor(uint256)': FunctionFragment
    'usdcAddress()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'MINTER_ROLE'
      | 'batchChargeTrialAndFeeUsdc'
      | 'chargeFeeUsdc'
      | 'chargeTrialUsdc'
      | 'isMinterContract'
      | 'isProfitValid'
      | 'isValidContractForFundOwner'
      | 'isValidSubmitterForFundOwner'
      | 'payoutUsdc'
      | 'riskFactor'
      | 'setAllowedContracts'
      | 'setAllowedSubmitter'
      | 'setRiskFactor'
      | 'usdcAddress'
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'MINTER_ROLE', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'batchChargeTrialAndFeeUsdc',
    values: [string, string, BigNumberish, BigNumberish, string]
  ): string
  encodeFunctionData(
    functionFragment: 'chargeFeeUsdc',
    values: [string, string, BigNumberish, string]
  ): string
  encodeFunctionData(
    functionFragment: 'chargeTrialUsdc',
    values: [string, string, BigNumberish]
  ): string
  encodeFunctionData(functionFragment: 'isMinterContract', values: [string]): string
  encodeFunctionData(functionFragment: 'isProfitValid', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'isValidContractForFundOwner',
    values: [string, string]
  ): string
  encodeFunctionData(
    functionFragment: 'isValidSubmitterForFundOwner',
    values: [string, string]
  ): string
  encodeFunctionData(functionFragment: 'payoutUsdc', values: [string, BigNumberish]): string
  encodeFunctionData(functionFragment: 'riskFactor', values?: undefined): string
  encodeFunctionData(functionFragment: 'setAllowedContracts', values: [string[], boolean[]]): string
  encodeFunctionData(functionFragment: 'setAllowedSubmitter', values: [string, boolean]): string
  encodeFunctionData(functionFragment: 'setRiskFactor', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'usdcAddress', values?: undefined): string

  decodeFunctionResult(functionFragment: 'MINTER_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'batchChargeTrialAndFeeUsdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'chargeFeeUsdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'chargeTrialUsdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isMinterContract', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isProfitValid', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isValidContractForFundOwner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isValidSubmitterForFundOwner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'payoutUsdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'riskFactor', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setAllowedContracts', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setAllowedSubmitter', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setRiskFactor', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'usdcAddress', data: BytesLike): Result

  events: {
    'AllowedContractsSet(address,address[],bool[])': EventFragment
    'AllowedSubmitterSet(address,address,bool)': EventFragment
    'RiskFactorSet(uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'AllowedContractsSet'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'AllowedSubmitterSet'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RiskFactorSet'): EventFragment
}

interface AllowedContractsSetEventObject {
  fundOwnerAddress: string
  contractAddresses: string[]
  isAlloweds: boolean[]
}

type AllowedContractsSetEvent = TypedEvent<
  [string, string[], boolean[]],
  AllowedContractsSetEventObject
>

type AllowedContractsSetEventFilter = TypedEventFilter<AllowedContractsSetEvent>

interface AllowedSubmitterSetEventObject {
  fundOwnerAddress: string
  submitterAddress: string
  isAllowed: boolean
}

type AllowedSubmitterSetEvent = TypedEvent<
  [string, string, boolean],
  AllowedSubmitterSetEventObject
>

type AllowedSubmitterSetEventFilter = TypedEventFilter<AllowedSubmitterSetEvent>

interface RiskFactorSetEventObject {
  newRiskFactor: BigNumber
}

type RiskFactorSetEvent = TypedEvent<[BigNumber], RiskFactorSetEventObject>

type RiskFactorSetEventFilter = TypedEventFilter<RiskFactorSetEvent>

export interface IFareAA extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: IFareAAInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    MINTER_ROLE(overrides?: CallOverrides): Promise<[string]>

    batchChargeTrialAndFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      collectAmount: BigNumberish,
      feeAmount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    chargeFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    chargeTrialUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    isMinterContract(contractAddress: string, overrides?: CallOverrides): Promise<[boolean]>

    isProfitValid(
      potentialProfitAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    isValidContractForFundOwner(
      contractAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    isValidSubmitterForFundOwner(
      submitterAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    payoutUsdc(
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    riskFactor(overrides?: CallOverrides): Promise<[BigNumber]>

    setAllowedContracts(
      contractAddresses: string[],
      isAlloweds: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    setAllowedSubmitter(
      submitterAddress: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    setRiskFactor(
      _riskFactor: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    usdcAddress(overrides?: CallOverrides): Promise<[string]>
  }

  MINTER_ROLE(overrides?: CallOverrides): Promise<string>

  batchChargeTrialAndFeeUsdc(
    submitterAddress: string,
    fundOwnerAddress: string,
    collectAmount: BigNumberish,
    feeAmount: BigNumberish,
    receiverAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  chargeFeeUsdc(
    submitterAddress: string,
    fundOwnerAddress: string,
    amount: BigNumberish,
    receiverAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  chargeTrialUsdc(
    submitterAddress: string,
    fundOwnerAddress: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  isMinterContract(contractAddress: string, overrides?: CallOverrides): Promise<boolean>

  isProfitValid(
    potentialProfitAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  isValidContractForFundOwner(
    contractAddress: string,
    fundOwnerAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  isValidSubmitterForFundOwner(
    submitterAddress: string,
    fundOwnerAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  payoutUsdc(
    fundOwnerAddress: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  riskFactor(overrides?: CallOverrides): Promise<BigNumber>

  setAllowedContracts(
    contractAddresses: string[],
    isAlloweds: boolean[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  setAllowedSubmitter(
    submitterAddress: string,
    isAllowed: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  setRiskFactor(
    _riskFactor: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  usdcAddress(overrides?: CallOverrides): Promise<string>

  callStatic: {
    MINTER_ROLE(overrides?: CallOverrides): Promise<string>

    batchChargeTrialAndFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      collectAmount: BigNumberish,
      feeAmount: BigNumberish,
      receiverAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    chargeFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      receiverAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    chargeTrialUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    isMinterContract(contractAddress: string, overrides?: CallOverrides): Promise<boolean>

    isProfitValid(potentialProfitAmount: BigNumberish, overrides?: CallOverrides): Promise<boolean>

    isValidContractForFundOwner(
      contractAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    isValidSubmitterForFundOwner(
      submitterAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    payoutUsdc(
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    riskFactor(overrides?: CallOverrides): Promise<BigNumber>

    setAllowedContracts(
      contractAddresses: string[],
      isAlloweds: boolean[],
      overrides?: CallOverrides
    ): Promise<void>

    setAllowedSubmitter(
      submitterAddress: string,
      isAllowed: boolean,
      overrides?: CallOverrides
    ): Promise<void>

    setRiskFactor(_riskFactor: BigNumberish, overrides?: CallOverrides): Promise<void>

    usdcAddress(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    'AllowedContractsSet(address,address[],bool[])'(
      fundOwnerAddress?: string | null,
      contractAddresses?: string[] | null,
      isAlloweds?: null
    ): AllowedContractsSetEventFilter
    AllowedContractsSet(
      fundOwnerAddress?: string | null,
      contractAddresses?: string[] | null,
      isAlloweds?: null
    ): AllowedContractsSetEventFilter

    'AllowedSubmitterSet(address,address,bool)'(
      fundOwnerAddress?: string | null,
      submitterAddress?: string | null,
      isAllowed?: null
    ): AllowedSubmitterSetEventFilter
    AllowedSubmitterSet(
      fundOwnerAddress?: string | null,
      submitterAddress?: string | null,
      isAllowed?: null
    ): AllowedSubmitterSetEventFilter

    'RiskFactorSet(uint256)'(newRiskFactor?: null): RiskFactorSetEventFilter
    RiskFactorSet(newRiskFactor?: null): RiskFactorSetEventFilter
  }

  estimateGas: {
    MINTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    batchChargeTrialAndFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      collectAmount: BigNumberish,
      feeAmount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    chargeFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    chargeTrialUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    isMinterContract(contractAddress: string, overrides?: CallOverrides): Promise<BigNumber>

    isProfitValid(
      potentialProfitAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    isValidContractForFundOwner(
      contractAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    isValidSubmitterForFundOwner(
      submitterAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    payoutUsdc(
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    riskFactor(overrides?: CallOverrides): Promise<BigNumber>

    setAllowedContracts(
      contractAddresses: string[],
      isAlloweds: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    setAllowedSubmitter(
      submitterAddress: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    setRiskFactor(
      _riskFactor: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    usdcAddress(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    MINTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    batchChargeTrialAndFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      collectAmount: BigNumberish,
      feeAmount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    chargeFeeUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      receiverAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    chargeTrialUsdc(
      submitterAddress: string,
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    isMinterContract(
      contractAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isProfitValid(
      potentialProfitAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    isValidContractForFundOwner(
      contractAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isValidSubmitterForFundOwner(
      submitterAddress: string,
      fundOwnerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    payoutUsdc(
      fundOwnerAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    riskFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>

    setAllowedContracts(
      contractAddresses: string[],
      isAlloweds: boolean[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    setAllowedSubmitter(
      submitterAddress: string,
      isAllowed: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    setRiskFactor(
      _riskFactor: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    usdcAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
