// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common'

export declare namespace UsdcVault {
  export type UsdcVaultParamsStruct = {
    fareAAAddress: string
    evThreshold: BigNumberish
    rngTimeout: BigNumberish
    feeRecipientAddress: string
    ethUsdcPrice: BigNumberish
    averageCallbackGas: BigNumberish
    aaCostMultiplier: BigNumberish
    vrfWrapperAddress: string
    keyHash: BytesLike
    subscriptionId: BigNumberish
    minimumRequestConfirmations: BigNumberish
    callbackGasLimit: BigNumberish
    vrfCoordinatorAddress: string
    useNativePayment: boolean
  }

  export type UsdcVaultParamsStructOutput = [
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    number,
    number,
    string,
    string,
    BigNumber,
    number,
    number,
    string,
    boolean,
  ] & {
    fareAAAddress: string
    evThreshold: BigNumber
    rngTimeout: BigNumber
    feeRecipientAddress: string
    ethUsdcPrice: BigNumber
    averageCallbackGas: number
    aaCostMultiplier: number
    vrfWrapperAddress: string
    keyHash: string
    subscriptionId: BigNumber
    minimumRequestConfirmations: number
    callbackGasLimit: number
    vrfCoordinatorAddress: string
    useNativePayment: boolean
  }

  export type ConfigParamsStruct = {
    ownerAddress: string
    usdcAddress: string
    fareAAAddress: string
    evThreshold: BigNumberish
    rngTimeout: BigNumberish
    feeRecipientAddress: string
    ethUsdcPrice: BigNumberish
    averageCallbackGas: BigNumberish
    aaCostMultiplier: BigNumberish
    vrfWrapperAddress: string
  }

  export type ConfigParamsStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    number,
    number,
    string,
  ] & {
    ownerAddress: string
    usdcAddress: string
    fareAAAddress: string
    evThreshold: BigNumber
    rngTimeout: BigNumber
    feeRecipientAddress: string
    ethUsdcPrice: BigNumber
    averageCallbackGas: number
    aaCostMultiplier: number
    vrfWrapperAddress: string
  }

  export type TrialStruct = {
    who: string
    timestamp: BigNumberish
    multiplier: BigNumberish
    evThreshold: BigNumberish
    q: BigNumberish[]
    k: BigNumberish[]
  }

  export type TrialStructOutput = [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber[],
    BigNumber[],
  ] & {
    who: string
    timestamp: BigNumber
    multiplier: BigNumber
    evThreshold: BigNumber
    q: BigNumber[]
    k: BigNumber[]
  }
}

export interface UsdcVaultInterface extends utils.Interface {
  functions: {
    'DEFAULT_ADMIN_ROLE()': FunctionFragment
    'RESOLVER_ROLE()': FunctionFragment
    'aaCostMultiplier()': FunctionFragment
    'acceptOwnership()': FunctionFragment
    'averageCallbackGas()': FunctionFragment
    'callbackGasLimit()': FunctionFragment
    'configUpdate_aaCostMultiplier(uint8)': FunctionFragment
    'configUpdate_averageCallbackGas(uint32)': FunctionFragment
    'configUpdate_ethUsdcPrice(uint216)': FunctionFragment
    'configUpdate_evThreshold(uint256)': FunctionFragment
    'configUpdate_fareAA(address)': FunctionFragment
    'configUpdate_feeRecipientAddress(address)': FunctionFragment
    'configUpdate_vrfWrapper(address)': FunctionFragment
    'configView()': FunctionFragment
    'ethUsdcPrice()': FunctionFragment
    'evThreshold()': FunctionFragment
    'extraordinaryResolve(uint256)': FunctionFragment
    'fareAA()': FunctionFragment
    'feeRecipientAddress()': FunctionFragment
    'getRoleAdmin(bytes32)': FunctionFragment
    'getRoleMember(bytes32,uint256)': FunctionFragment
    'getRoleMemberCount(bytes32)': FunctionFragment
    'getTrial(uint256)': FunctionFragment
    'grantRole(bytes32,address)': FunctionFragment
    'hasRole(bytes32,address)': FunctionFragment
    'keyHash()': FunctionFragment
    'minimumRequestConfirmations()': FunctionFragment
    'owner()': FunctionFragment
    'packMaxValues(uint216,uint32,uint8)': FunctionFragment
    'rawFulfillRandomWords(uint256,uint256[])': FunctionFragment
    'renounceRole(bytes32,address)': FunctionFragment
    'revokeRole(bytes32,address)': FunctionFragment
    'rngTimeout()': FunctionFragment
    's_vrfCoordinator()': FunctionFragment
    'setCoordinator(address)': FunctionFragment
    'subscriptionId()': FunctionFragment
    'supportsInterface(bytes4)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'trialIdToTrial(uint256)': FunctionFragment
    'trialRegister(address,uint256,uint256[],uint256[],uint256)': FunctionFragment
    'unpackMaxValues(uint256)': FunctionFragment
    'usdc()': FunctionFragment
    'useNativePayment()': FunctionFragment
    'vrfConfigUpdate(bytes32,uint256,uint16,uint32,bool)': FunctionFragment
    'vrfConfigView()': FunctionFragment
    'vrfWrapper()': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'DEFAULT_ADMIN_ROLE'
      | 'RESOLVER_ROLE'
      | 'aaCostMultiplier'
      | 'acceptOwnership'
      | 'averageCallbackGas'
      | 'callbackGasLimit'
      | 'configUpdate_aaCostMultiplier'
      | 'configUpdate_averageCallbackGas'
      | 'configUpdate_ethUsdcPrice'
      | 'configUpdate_evThreshold'
      | 'configUpdate_fareAA'
      | 'configUpdate_feeRecipientAddress'
      | 'configUpdate_vrfWrapper'
      | 'configView'
      | 'ethUsdcPrice'
      | 'evThreshold'
      | 'extraordinaryResolve'
      | 'fareAA'
      | 'feeRecipientAddress'
      | 'getRoleAdmin'
      | 'getRoleMember'
      | 'getRoleMemberCount'
      | 'getTrial'
      | 'grantRole'
      | 'hasRole'
      | 'keyHash'
      | 'minimumRequestConfirmations'
      | 'owner'
      | 'packMaxValues'
      | 'rawFulfillRandomWords'
      | 'renounceRole'
      | 'revokeRole'
      | 'rngTimeout'
      | 's_vrfCoordinator'
      | 'setCoordinator'
      | 'subscriptionId'
      | 'supportsInterface'
      | 'transferOwnership'
      | 'trialIdToTrial'
      | 'trialRegister'
      | 'unpackMaxValues'
      | 'usdc'
      | 'useNativePayment'
      | 'vrfConfigUpdate'
      | 'vrfConfigView'
      | 'vrfWrapper'
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string
  encodeFunctionData(functionFragment: 'RESOLVER_ROLE', values?: undefined): string
  encodeFunctionData(functionFragment: 'aaCostMultiplier', values?: undefined): string
  encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string
  encodeFunctionData(functionFragment: 'averageCallbackGas', values?: undefined): string
  encodeFunctionData(functionFragment: 'callbackGasLimit', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'configUpdate_aaCostMultiplier',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'configUpdate_averageCallbackGas',
    values: [BigNumberish]
  ): string
  encodeFunctionData(functionFragment: 'configUpdate_ethUsdcPrice', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'configUpdate_evThreshold', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'configUpdate_fareAA', values: [string]): string
  encodeFunctionData(functionFragment: 'configUpdate_feeRecipientAddress', values: [string]): string
  encodeFunctionData(functionFragment: 'configUpdate_vrfWrapper', values: [string]): string
  encodeFunctionData(functionFragment: 'configView', values?: undefined): string
  encodeFunctionData(functionFragment: 'ethUsdcPrice', values?: undefined): string
  encodeFunctionData(functionFragment: 'evThreshold', values?: undefined): string
  encodeFunctionData(functionFragment: 'extraordinaryResolve', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'fareAA', values?: undefined): string
  encodeFunctionData(functionFragment: 'feeRecipientAddress', values?: undefined): string
  encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getRoleMember', values: [BytesLike, BigNumberish]): string
  encodeFunctionData(functionFragment: 'getRoleMemberCount', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'getTrial', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'keyHash', values?: undefined): string
  encodeFunctionData(functionFragment: 'minimumRequestConfirmations', values?: undefined): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'packMaxValues',
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'rawFulfillRandomWords',
    values: [BigNumberish, BigNumberish[]]
  ): string
  encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, string]): string
  encodeFunctionData(functionFragment: 'rngTimeout', values?: undefined): string
  encodeFunctionData(functionFragment: 's_vrfCoordinator', values?: undefined): string
  encodeFunctionData(functionFragment: 'setCoordinator', values: [string]): string
  encodeFunctionData(functionFragment: 'subscriptionId', values?: undefined): string
  encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string
  encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string
  encodeFunctionData(functionFragment: 'trialIdToTrial', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'trialRegister',
    values: [string, BigNumberish, BigNumberish[], BigNumberish[], BigNumberish]
  ): string
  encodeFunctionData(functionFragment: 'unpackMaxValues', values: [BigNumberish]): string
  encodeFunctionData(functionFragment: 'usdc', values?: undefined): string
  encodeFunctionData(functionFragment: 'useNativePayment', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'vrfConfigUpdate',
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string
  encodeFunctionData(functionFragment: 'vrfConfigView', values?: undefined): string
  encodeFunctionData(functionFragment: 'vrfWrapper', values?: undefined): string

  decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'RESOLVER_ROLE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'aaCostMultiplier', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'averageCallbackGas', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'callbackGasLimit', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_aaCostMultiplier', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_averageCallbackGas', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_ethUsdcPrice', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_evThreshold', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configUpdate_fareAA', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'configUpdate_feeRecipientAddress',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'configUpdate_vrfWrapper', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'configView', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'ethUsdcPrice', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'evThreshold', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'extraordinaryResolve', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'fareAA', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'feeRecipientAddress', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMember', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getRoleMemberCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getTrial', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'keyHash', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'minimumRequestConfirmations', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'packMaxValues', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rawFulfillRandomWords', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rngTimeout', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 's_vrfCoordinator', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setCoordinator', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'subscriptionId', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'trialIdToTrial', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'trialRegister', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'unpackMaxValues', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'useNativePayment', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vrfConfigUpdate', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vrfConfigView', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'vrfWrapper', data: BytesLike): Result

  events: {
    'AACostMultiplierUpdated(uint8)': EventFragment
    'AverageCallbackGasUpdated(uint32)': EventFragment
    'CoordinatorSet(address)': EventFragment
    'EVThresholdUpdated(uint256)': EventFragment
    'EthUsdcPriceUpdated(uint216)': EventFragment
    'FareAAUpdated(address)': EventFragment
    'FeeRecipientAddressUpdated(address)': EventFragment
    'OwnershipTransferRequested(address,address)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
    'RoleAdminChanged(bytes32,bytes32,bytes32)': EventFragment
    'RoleGranted(bytes32,address,address)': EventFragment
    'RoleRevoked(bytes32,address,address)': EventFragment
    'TrialRegistered(uint256,address,address,uint256,uint256[],uint256[],uint256,uint256)': EventFragment
    'TrialResolved(uint256,uint256,uint256,uint256)': EventFragment
    'VRFWrapperUpdated(address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'AACostMultiplierUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'AverageCallbackGasUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'CoordinatorSet'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'EVThresholdUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'EthUsdcPriceUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'FareAAUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'FeeRecipientAddressUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferRequested'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleAdminChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleGranted'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RoleRevoked'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'TrialRegistered'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'TrialResolved'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'VRFWrapperUpdated'): EventFragment
}

interface AACostMultiplierUpdatedEventObject {
  newAACostMultiplier: number
}

type AACostMultiplierUpdatedEvent = TypedEvent<[number], AACostMultiplierUpdatedEventObject>

type AACostMultiplierUpdatedEventFilter = TypedEventFilter<AACostMultiplierUpdatedEvent>
interface AverageCallbackGasUpdatedEventObject {
  newAverageCallbackGas: number
}

type AverageCallbackGasUpdatedEvent = TypedEvent<
  [number],
  AverageCallbackGasUpdatedEventObject
>

type AverageCallbackGasUpdatedEventFilter = TypedEventFilter<AverageCallbackGasUpdatedEvent>
interface CoordinatorSetEventObject {
  vrfCoordinator: string
}

type CoordinatorSetEvent = TypedEvent<[string], CoordinatorSetEventObject>

type CoordinatorSetEventFilter = TypedEventFilter<CoordinatorSetEvent>
interface EVThresholdUpdatedEventObject {
  newEVThreshold: BigNumber
}

type EVThresholdUpdatedEvent = TypedEvent<[BigNumber], EVThresholdUpdatedEventObject>

type EVThresholdUpdatedEventFilter = TypedEventFilter<EVThresholdUpdatedEvent>
interface EthUsdcPriceUpdatedEventObject {
  newEthFarePrice: BigNumber
}

type EthUsdcPriceUpdatedEvent = TypedEvent<[BigNumber], EthUsdcPriceUpdatedEventObject>

type EthUsdcPriceUpdatedEventFilter = TypedEventFilter<EthUsdcPriceUpdatedEvent>
interface FareAAUpdatedEventObject {
  newFareAAAddress: string
}

type FareAAUpdatedEvent = TypedEvent<[string], FareAAUpdatedEventObject>

type FareAAUpdatedEventFilter = TypedEventFilter<FareAAUpdatedEvent>

interface FeeRecipientAddressUpdatedEventObject {
  newFeeRecipientAddress: string
}

type FeeRecipientAddressUpdatedEvent = TypedEvent<
  [string],
  FeeRecipientAddressUpdatedEventObject
>

type FeeRecipientAddressUpdatedEventFilter =
  TypedEventFilter<FeeRecipientAddressUpdatedEvent>
interface OwnershipTransferRequestedEventObject {
  from: string
  to: string
}

type OwnershipTransferRequestedEvent = TypedEvent<
  [string, string],
  OwnershipTransferRequestedEventObject
>

type OwnershipTransferRequestedEventFilter =
  TypedEventFilter<OwnershipTransferRequestedEvent>
interface OwnershipTransferredEventObject {
  from: string
  to: string
}

type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>

type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>

interface RoleAdminChangedEventObject {
  role: string
  previousAdminRole: string
  newAdminRole: string
}

type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>

type RoleAdminChangedEventFilter = TypedEventFilter<RoleAdminChangedEvent>

interface RoleGrantedEventObject {
  role: string
  account: string
  sender: string
}

type RoleGrantedEvent = TypedEvent<[string, string, string], RoleGrantedEventObject>

type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>
interface RoleRevokedEventObject {
  role: string
  account: string
  sender: string
}

type RoleRevokedEvent = TypedEvent<[string, string, string], RoleRevokedEventObject>

type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>
interface TrialRegisteredEventObject {
  trialId: BigNumber
  who: string
  submitter: string
  multiplier: BigNumber
  q: BigNumber[]
  k: BigNumber[]
  vrfCostInUsdc: BigNumber
  aaCostInUsdc: BigNumber
}

type TrialRegisteredEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber[], BigNumber[], BigNumber, BigNumber],
  TrialRegisteredEventObject
>

type TrialRegisteredEventFilter = TypedEventFilter<TrialRegisteredEvent>
interface TrialResolvedEventObject {
  trialId: BigNumber
  resultIndex: BigNumber
  evThreshold: BigNumber
  randomness: BigNumber
}

type TrialResolvedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  TrialResolvedEventObject
>

type TrialResolvedEventFilter = TypedEventFilter<TrialResolvedEvent>
interface VRFWrapperUpdatedEventObject {
  newVRFWrapperAddress: string
}

type VRFWrapperUpdatedEvent = TypedEvent<[string], VRFWrapperUpdatedEventObject>

type VRFWrapperUpdatedEventFilter = TypedEventFilter<VRFWrapperUpdatedEvent>

export interface UsdcVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: UsdcVaultInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>

    RESOLVER_ROLE(overrides?: CallOverrides): Promise<[string]>

    aaCostMultiplier(overrides?: CallOverrides): Promise<[number]>

    acceptOwnership(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

    averageCallbackGas(overrides?: CallOverrides): Promise<[number]>

    callbackGasLimit(overrides?: CallOverrides): Promise<[number]>

    configUpdate_aaCostMultiplier(
      _aaCostMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_averageCallbackGas(
      _averageCallbackGas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_ethUsdcPrice(
      _ethUsdcPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_evThreshold(
      _evThreshold: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_fareAA(
      _fareAAAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_feeRecipientAddress(
      _feeRecipientAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configUpdate_vrfWrapper(
      _vrfWrapperAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    configView(overrides?: CallOverrides): Promise<[UsdcVault.ConfigParamsStructOutput]>

    ethUsdcPrice(overrides?: CallOverrides): Promise<[BigNumber]>

    evThreshold(overrides?: CallOverrides): Promise<[BigNumber]>

    extraordinaryResolve(
      trialId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    fareAA(overrides?: CallOverrides): Promise<[string]>

    feeRecipientAddress(overrides?: CallOverrides): Promise<[string]>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>

    getTrial(
      trialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[UsdcVault.TrialStructOutput]>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<[boolean]>

    keyHash(overrides?: CallOverrides): Promise<[string]>

    minimumRequestConfirmations(overrides?: CallOverrides): Promise<[number]>

    owner(overrides?: CallOverrides): Promise<[string]>

    packMaxValues(
      maxEthUsdcPrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      maxAACostMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    rngTimeout(overrides?: CallOverrides): Promise<[BigNumber]>

    s_vrfCoordinator(overrides?: CallOverrides): Promise<[string]>

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    subscriptionId(overrides?: CallOverrides): Promise<[BigNumber]>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<[boolean]>

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    trialIdToTrial(
      trialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        who: string
        timestamp: BigNumber
        multiplier: BigNumber
        evThreshold: BigNumber
      }
    >

    trialRegister(
      who: string,
      multiplier: BigNumberish,
      q: BigNumberish[],
      k: BigNumberish[],
      packedMaxValues: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    unpackMaxValues(
      packedMaxValues: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>

    usdc(overrides?: CallOverrides): Promise<[string]>

    useNativePayment(overrides?: CallOverrides): Promise<[boolean]>

    vrfConfigUpdate(
      _keyHash: BytesLike,
      _subscriptionId: BigNumberish,
      _minimumRequestConfirmations: BigNumberish,
      _callbackGasLimit: BigNumberish,
      _useNativePayment: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>

    vrfConfigView(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, number, number, boolean]>

    vrfWrapper(overrides?: CallOverrides): Promise<[string]>
  }

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

  RESOLVER_ROLE(overrides?: CallOverrides): Promise<string>

  aaCostMultiplier(overrides?: CallOverrides): Promise<number>

  acceptOwnership(overrides?: Overrides & { from?: string }): Promise<ContractTransaction>

  averageCallbackGas(overrides?: CallOverrides): Promise<number>

  callbackGasLimit(overrides?: CallOverrides): Promise<number>

  configUpdate_aaCostMultiplier(
    _aaCostMultiplier: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_averageCallbackGas(
    _averageCallbackGas: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_ethUsdcPrice(
    _ethUsdcPrice: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_evThreshold(
    _evThreshold: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_fareAA(
    _fareAAAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_feeRecipientAddress(
    _feeRecipientAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configUpdate_vrfWrapper(
    _vrfWrapperAddress: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  configView(overrides?: CallOverrides): Promise<UsdcVault.ConfigParamsStructOutput>

  ethUsdcPrice(overrides?: CallOverrides): Promise<BigNumber>

  evThreshold(overrides?: CallOverrides): Promise<BigNumber>

  extraordinaryResolve(
    trialId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  fareAA(overrides?: CallOverrides): Promise<string>

  feeRecipientAddress(overrides?: CallOverrides): Promise<string>

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

  getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

  getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

  getTrial(trialId: BigNumberish, overrides?: CallOverrides): Promise<UsdcVault.TrialStructOutput>

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

  keyHash(overrides?: CallOverrides): Promise<string>

  minimumRequestConfirmations(overrides?: CallOverrides): Promise<number>

  owner(overrides?: CallOverrides): Promise<string>

  packMaxValues(
    maxEthUsdcPrice: BigNumberish,
    maxAverageCallbackGas: BigNumberish,
    maxAACostMultiplier: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  rawFulfillRandomWords(
    requestId: BigNumberish,
    randomWords: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  renounceRole(
    role: BytesLike,
    callerConfirmation: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  rngTimeout(overrides?: CallOverrides): Promise<BigNumber>

  s_vrfCoordinator(overrides?: CallOverrides): Promise<string>

  setCoordinator(
    _vrfCoordinator: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  subscriptionId(overrides?: CallOverrides): Promise<BigNumber>

  supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

  transferOwnership(
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  trialIdToTrial(
    trialId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      who: string
      timestamp: BigNumber
      multiplier: BigNumber
      evThreshold: BigNumber
    }
  >

  trialRegister(
    who: string,
    multiplier: BigNumberish,
    q: BigNumberish[],
    k: BigNumberish[],
    packedMaxValues: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  unpackMaxValues(
    packedMaxValues: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>

  usdc(overrides?: CallOverrides): Promise<string>

  useNativePayment(overrides?: CallOverrides): Promise<boolean>

  vrfConfigUpdate(
    _keyHash: BytesLike,
    _subscriptionId: BigNumberish,
    _minimumRequestConfirmations: BigNumberish,
    _callbackGasLimit: BigNumberish,
    _useNativePayment: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>

  vrfConfigView(
    overrides?: CallOverrides
  ): Promise<[string, string, BigNumber, number, number, boolean]>

  vrfWrapper(overrides?: CallOverrides): Promise<string>

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>

    RESOLVER_ROLE(overrides?: CallOverrides): Promise<string>

    aaCostMultiplier(overrides?: CallOverrides): Promise<number>

    acceptOwnership(overrides?: CallOverrides): Promise<void>

    averageCallbackGas(overrides?: CallOverrides): Promise<number>

    callbackGasLimit(overrides?: CallOverrides): Promise<number>

    configUpdate_aaCostMultiplier(
      _aaCostMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    configUpdate_averageCallbackGas(
      _averageCallbackGas: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>

    configUpdate_ethUsdcPrice(_ethUsdcPrice: BigNumberish, overrides?: CallOverrides): Promise<void>

    configUpdate_evThreshold(_evThreshold: BigNumberish, overrides?: CallOverrides): Promise<void>

    configUpdate_fareAA(_fareAAAddress: string, overrides?: CallOverrides): Promise<void>

    configUpdate_feeRecipientAddress(
      _feeRecipientAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    configUpdate_vrfWrapper(_vrfWrapperAddress: string, overrides?: CallOverrides): Promise<void>

    configView(overrides?: CallOverrides): Promise<UsdcVault.ConfigParamsStructOutput>

    ethUsdcPrice(overrides?: CallOverrides): Promise<BigNumber>

    evThreshold(overrides?: CallOverrides): Promise<BigNumber>

    extraordinaryResolve(trialId: BigNumberish, overrides?: CallOverrides): Promise<void>

    fareAA(overrides?: CallOverrides): Promise<string>

    feeRecipientAddress(overrides?: CallOverrides): Promise<string>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>

    getRoleMember(role: BytesLike, index: BigNumberish, overrides?: CallOverrides): Promise<string>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getTrial(trialId: BigNumberish, overrides?: CallOverrides): Promise<UsdcVault.TrialStructOutput>

    grantRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<boolean>

    keyHash(overrides?: CallOverrides): Promise<string>

    minimumRequestConfirmations(overrides?: CallOverrides): Promise<number>

    owner(overrides?: CallOverrides): Promise<string>

    packMaxValues(
      maxEthUsdcPrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      maxAACostMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: CallOverrides
    ): Promise<void>

    revokeRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<void>

    rngTimeout(overrides?: CallOverrides): Promise<BigNumber>

    s_vrfCoordinator(overrides?: CallOverrides): Promise<string>

    setCoordinator(_vrfCoordinator: string, overrides?: CallOverrides): Promise<void>

    subscriptionId(overrides?: CallOverrides): Promise<BigNumber>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

    transferOwnership(to: string, overrides?: CallOverrides): Promise<void>

    trialIdToTrial(
      trialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        who: string
        timestamp: BigNumber
        multiplier: BigNumber
        evThreshold: BigNumber
      }
    >

    trialRegister(
      who: string,
      multiplier: BigNumberish,
      q: BigNumberish[],
      k: BigNumberish[],
      packedMaxValues: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    unpackMaxValues(
      packedMaxValues: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>

    usdc(overrides?: CallOverrides): Promise<string>

    useNativePayment(overrides?: CallOverrides): Promise<boolean>

    vrfConfigUpdate(
      _keyHash: BytesLike,
      _subscriptionId: BigNumberish,
      _minimumRequestConfirmations: BigNumberish,
      _callbackGasLimit: BigNumberish,
      _useNativePayment: boolean,
      overrides?: CallOverrides
    ): Promise<void>

    vrfConfigView(
      overrides?: CallOverrides
    ): Promise<[string, string, BigNumber, number, number, boolean]>

    vrfWrapper(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    'AACostMultiplierUpdated(uint8)'(newAACostMultiplier?: null): AACostMultiplierUpdatedEventFilter
    AACostMultiplierUpdated(newAACostMultiplier?: null): AACostMultiplierUpdatedEventFilter

    'AverageCallbackGasUpdated(uint32)'(
      newAverageCallbackGas?: null
    ): AverageCallbackGasUpdatedEventFilter
    AverageCallbackGasUpdated(newAverageCallbackGas?: null): AverageCallbackGasUpdatedEventFilter

    'CoordinatorSet(address)'(vrfCoordinator?: null): CoordinatorSetEventFilter
    CoordinatorSet(vrfCoordinator?: null): CoordinatorSetEventFilter

    'EVThresholdUpdated(uint256)'(newEVThreshold?: null): EVThresholdUpdatedEventFilter
    EVThresholdUpdated(newEVThreshold?: null): EVThresholdUpdatedEventFilter

    'EthUsdcPriceUpdated(uint216)'(newEthFarePrice?: null): EthUsdcPriceUpdatedEventFilter
    EthUsdcPriceUpdated(newEthFarePrice?: null): EthUsdcPriceUpdatedEventFilter

    'FareAAUpdated(address)'(newFareAAAddress?: null): FareAAUpdatedEventFilter
    FareAAUpdated(newFareAAAddress?: null): FareAAUpdatedEventFilter

    'FeeRecipientAddressUpdated(address)'(
      newFeeRecipientAddress?: null
    ): FeeRecipientAddressUpdatedEventFilter
    FeeRecipientAddressUpdated(newFeeRecipientAddress?: null): FeeRecipientAddressUpdatedEventFilter

    'OwnershipTransferRequested(address,address)'(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferRequestedEventFilter
    OwnershipTransferRequested(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferRequestedEventFilter

    'OwnershipTransferred(address,address)'(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(from?: string | null, to?: string | null): OwnershipTransferredEventFilter

    'RoleAdminChanged(bytes32,bytes32,bytes32)'(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter

    'RoleGranted(bytes32,address,address)'(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter

    'RoleRevoked(bytes32,address,address)'(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter

    'TrialRegistered(uint256,address,address,uint256,uint256[],uint256[],uint256,uint256)'(
      trialId?: BigNumberish | null,
      who?: string | null,
      submitter?: string | null,
      multiplier?: null,
      q?: null,
      k?: null,
      vrfCostInUsdc?: null,
      aaCostInUsdc?: null
    ): TrialRegisteredEventFilter
    TrialRegistered(
      trialId?: BigNumberish | null,
      who?: string | null,
      submitter?: string | null,
      multiplier?: null,
      q?: null,
      k?: null,
      vrfCostInUsdc?: null,
      aaCostInUsdc?: null
    ): TrialRegisteredEventFilter

    'TrialResolved(uint256,uint256,uint256,uint256)'(
      trialId?: BigNumberish | null,
      resultIndex?: null,
      evThreshold?: null,
      randomness?: null
    ): TrialResolvedEventFilter
    TrialResolved(
      trialId?: BigNumberish | null,
      resultIndex?: null,
      evThreshold?: null,
      randomness?: null
    ): TrialResolvedEventFilter

    'VRFWrapperUpdated(address)'(newVRFWrapperAddress?: null): VRFWrapperUpdatedEventFilter
    VRFWrapperUpdated(newVRFWrapperAddress?: null): VRFWrapperUpdatedEventFilter
  }

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    RESOLVER_ROLE(overrides?: CallOverrides): Promise<BigNumber>

    aaCostMultiplier(overrides?: CallOverrides): Promise<BigNumber>

    acceptOwnership(overrides?: Overrides & { from?: string }): Promise<BigNumber>

    averageCallbackGas(overrides?: CallOverrides): Promise<BigNumber>

    callbackGasLimit(overrides?: CallOverrides): Promise<BigNumber>

    configUpdate_aaCostMultiplier(
      _aaCostMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_averageCallbackGas(
      _averageCallbackGas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_ethUsdcPrice(
      _ethUsdcPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_evThreshold(
      _evThreshold: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_fareAA(
      _fareAAAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_feeRecipientAddress(
      _feeRecipientAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configUpdate_vrfWrapper(
      _vrfWrapperAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    configView(overrides?: CallOverrides): Promise<BigNumber>

    ethUsdcPrice(overrides?: CallOverrides): Promise<BigNumber>

    evThreshold(overrides?: CallOverrides): Promise<BigNumber>

    extraordinaryResolve(
      trialId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    fareAA(overrides?: CallOverrides): Promise<BigNumber>

    feeRecipientAddress(overrides?: CallOverrides): Promise<BigNumber>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    getTrial(trialId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    hasRole(role: BytesLike, account: string, overrides?: CallOverrides): Promise<BigNumber>

    keyHash(overrides?: CallOverrides): Promise<BigNumber>

    minimumRequestConfirmations(overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    packMaxValues(
      maxEthUsdcPrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      maxAACostMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    rngTimeout(overrides?: CallOverrides): Promise<BigNumber>

    s_vrfCoordinator(overrides?: CallOverrides): Promise<BigNumber>

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    subscriptionId(overrides?: CallOverrides): Promise<BigNumber>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

    transferOwnership(to: string, overrides?: Overrides & { from?: string }): Promise<BigNumber>

    trialIdToTrial(trialId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    trialRegister(
      who: string,
      multiplier: BigNumberish,
      q: BigNumberish[],
      k: BigNumberish[],
      packedMaxValues: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    unpackMaxValues(packedMaxValues: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    usdc(overrides?: CallOverrides): Promise<BigNumber>

    useNativePayment(overrides?: CallOverrides): Promise<BigNumber>

    vrfConfigUpdate(
      _keyHash: BytesLike,
      _subscriptionId: BigNumberish,
      _minimumRequestConfirmations: BigNumberish,
      _callbackGasLimit: BigNumberish,
      _useNativePayment: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>

    vrfConfigView(overrides?: CallOverrides): Promise<BigNumber>

    vrfWrapper(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    RESOLVER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    aaCostMultiplier(overrides?: CallOverrides): Promise<PopulatedTransaction>

    acceptOwnership(overrides?: Overrides & { from?: string }): Promise<PopulatedTransaction>

    averageCallbackGas(overrides?: CallOverrides): Promise<PopulatedTransaction>

    callbackGasLimit(overrides?: CallOverrides): Promise<PopulatedTransaction>

    configUpdate_aaCostMultiplier(
      _aaCostMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_averageCallbackGas(
      _averageCallbackGas: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_ethUsdcPrice(
      _ethUsdcPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_evThreshold(
      _evThreshold: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_fareAA(
      _fareAAAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_feeRecipientAddress(
      _feeRecipientAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configUpdate_vrfWrapper(
      _vrfWrapperAddress: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    configView(overrides?: CallOverrides): Promise<PopulatedTransaction>

    ethUsdcPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>

    evThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>

    extraordinaryResolve(
      trialId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    fareAA(overrides?: CallOverrides): Promise<PopulatedTransaction>

    feeRecipientAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getRoleMember(
      role: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getRoleMemberCount(role: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

    getTrial(trialId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    keyHash(overrides?: CallOverrides): Promise<PopulatedTransaction>

    minimumRequestConfirmations(overrides?: CallOverrides): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    packMaxValues(
      maxEthUsdcPrice: BigNumberish,
      maxAverageCallbackGas: BigNumberish,
      maxAACostMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    renounceRole(
      role: BytesLike,
      callerConfirmation: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    rngTimeout(overrides?: CallOverrides): Promise<PopulatedTransaction>

    s_vrfCoordinator(overrides?: CallOverrides): Promise<PopulatedTransaction>

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    subscriptionId(overrides?: CallOverrides): Promise<PopulatedTransaction>

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    trialIdToTrial(trialId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

    trialRegister(
      who: string,
      multiplier: BigNumberish,
      q: BigNumberish[],
      k: BigNumberish[],
      packedMaxValues: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    unpackMaxValues(
      packedMaxValues: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>

    useNativePayment(overrides?: CallOverrides): Promise<PopulatedTransaction>

    vrfConfigUpdate(
      _keyHash: BytesLike,
      _subscriptionId: BigNumberish,
      _minimumRequestConfirmations: BigNumberish,
      _callbackGasLimit: BigNumberish,
      _useNativePayment: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>

    vrfConfigView(overrides?: CallOverrides): Promise<PopulatedTransaction>

    vrfWrapper(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
