// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface VRFV2PlusWrapperInterface extends utils.Interface {
  functions: {
    "SUBSCRIPTION_ID()": FunctionFragment;
    "acceptOwnership()": FunctionFragment;
    "calculateRequestPrice(uint32,uint32)": FunctionFragment;
    "calculateRequestPriceNative(uint32,uint32)": FunctionFragment;
    "checkPaymentMode(bytes,bool)": FunctionFragment;
    "disable()": FunctionFragment;
    "enable()": FunctionFragment;
    "estimateRequestPrice(uint32,uint32,uint256)": FunctionFragment;
    "estimateRequestPriceNative(uint32,uint32,uint256)": FunctionFragment;
    "getConfig()": FunctionFragment;
    "lastRequestId()": FunctionFragment;
    "link()": FunctionFragment;
    "linkNativeFeed()": FunctionFragment;
    "onTokenTransfer(address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "rawFulfillRandomWords(uint256,uint256[])": FunctionFragment;
    "requestRandomWordsInNative(uint32,uint16,uint32,bytes)": FunctionFragment;
    "s_callbacks(uint256)": FunctionFragment;
    "s_configured()": FunctionFragment;
    "s_disabled()": FunctionFragment;
    "s_fulfillmentTxSizeBytes()": FunctionFragment;
    "s_vrfCoordinator()": FunctionFragment;
    "setConfig(uint32,uint32,uint32,uint16,uint8,uint8,bytes32,uint8,uint32,int256,uint32,uint32)": FunctionFragment;
    "setCoordinator(address)": FunctionFragment;
    "setFulfillmentTxSize(uint32)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "typeAndVersion()": FunctionFragment;
    "withdraw(address)": FunctionFragment;
    "withdrawNative(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "SUBSCRIPTION_ID"
      | "acceptOwnership"
      | "calculateRequestPrice"
      | "calculateRequestPriceNative"
      | "checkPaymentMode"
      | "disable"
      | "enable"
      | "estimateRequestPrice"
      | "estimateRequestPriceNative"
      | "getConfig"
      | "lastRequestId"
      | "link"
      | "linkNativeFeed"
      | "onTokenTransfer"
      | "owner"
      | "rawFulfillRandomWords"
      | "requestRandomWordsInNative"
      | "s_callbacks"
      | "s_configured"
      | "s_disabled"
      | "s_fulfillmentTxSizeBytes"
      | "s_vrfCoordinator"
      | "setConfig"
      | "setCoordinator"
      | "setFulfillmentTxSize"
      | "transferOwnership"
      | "typeAndVersion"
      | "withdraw"
      | "withdrawNative"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "SUBSCRIPTION_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequestPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequestPriceNative",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkPaymentMode",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "disable", values?: undefined): string;
  encodeFunctionData(functionFragment: "enable", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "estimateRequestPrice",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateRequestPriceNative",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "link", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "linkNativeFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onTokenTransfer",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomWordsInNative",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "s_callbacks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_configured",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_disabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_fulfillmentTxSizeBytes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_vrfCoordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setCoordinator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFulfillmentTxSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "typeAndVersion",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "SUBSCRIPTION_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequestPriceNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkPaymentMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "estimateRequestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateRequestPriceNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "link", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "linkNativeFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomWordsInNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_callbacks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_configured",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_disabled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_fulfillmentTxSizeBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_vrfCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFulfillmentTxSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "typeAndVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;

  events: {
    "ConfigSet(uint32,uint32,uint32,uint16,uint8,uint8,bytes32,uint8,uint32,int256,uint32,uint32)": EventFragment;
    "CoordinatorSet(address)": EventFragment;
    "Disabled()": EventFragment;
    "Enabled()": EventFragment;
    "FallbackWeiPerUnitLinkUsed(uint256,int256)": EventFragment;
    "FulfillmentTxSizeSet(uint32)": EventFragment;
    "NativeWithdrawn(address,uint256)": EventFragment;
    "OwnershipTransferRequested(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Withdrawn(address,uint256)": EventFragment;
    "WrapperFulfillmentFailed(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConfigSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CoordinatorSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Disabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Enabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FallbackWeiPerUnitLinkUsed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FulfillmentTxSizeSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NativeWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WrapperFulfillmentFailed"): EventFragment;
}

interface ConfigSetEventObject {
  wrapperGasOverhead: number;
  coordinatorGasOverheadNative: number;
  coordinatorGasOverheadLink: number;
  coordinatorGasOverheadPerWord: number;
  coordinatorNativePremiumPercentage: number;
  coordinatorLinkPremiumPercentage: number;
  keyHash: string;
  maxNumWords: number;
  stalenessSeconds: number;
  fallbackWeiPerUnitLink: BigNumber;
  fulfillmentFlatFeeNativePPM: number;
  fulfillmentFlatFeeLinkDiscountPPM: number;
}

type ConfigSetEvent = TypedEvent<
  [
    number,
    number,
    number,
    number,
    number,
    number,
    string,
    number,
    number,
    BigNumber,
    number,
    number
  ],
  ConfigSetEventObject
>;

type ConfigSetEventFilter = TypedEventFilter<ConfigSetEvent>;
interface CoordinatorSetEventObject {
  vrfCoordinator: string;
}

type CoordinatorSetEvent = TypedEvent<
  [string],
  CoordinatorSetEventObject
>;

type CoordinatorSetEventFilter = TypedEventFilter<CoordinatorSetEvent>;

interface DisabledEventObject {}
type DisabledEvent = TypedEvent<[], DisabledEventObject>;

type DisabledEventFilter = TypedEventFilter<DisabledEvent>;

interface EnabledEventObject {}
type EnabledEvent = TypedEvent<[], EnabledEventObject>;

type EnabledEventFilter = TypedEventFilter<EnabledEvent>;
interface FallbackWeiPerUnitLinkUsedEventObject {
  requestId: BigNumber;
  fallbackWeiPerUnitLink: BigNumber;
}

type FallbackWeiPerUnitLinkUsedEvent = TypedEvent<
  [BigNumber, BigNumber],
  FallbackWeiPerUnitLinkUsedEventObject
>;

type FallbackWeiPerUnitLinkUsedEventFilter =
  TypedEventFilter<FallbackWeiPerUnitLinkUsedEvent>;
interface FulfillmentTxSizeSetEventObject {
  size: number;
}

type FulfillmentTxSizeSetEvent = TypedEvent<
  [number],
  FulfillmentTxSizeSetEventObject
>;

type FulfillmentTxSizeSetEventFilter =
  TypedEventFilter<FulfillmentTxSizeSetEvent>;
interface NativeWithdrawnEventObject {
  to: string;
  amount: BigNumber;
}

type NativeWithdrawnEvent = TypedEvent<
  [string, BigNumber],
  NativeWithdrawnEventObject
>;

type NativeWithdrawnEventFilter = TypedEventFilter<NativeWithdrawnEvent>;
interface OwnershipTransferRequestedEventObject {
  from: string;
  to: string;
}

type OwnershipTransferRequestedEvent = TypedEvent<
  [string, string],
  OwnershipTransferRequestedEventObject
>;

type OwnershipTransferRequestedEventFilter =
  TypedEventFilter<OwnershipTransferRequestedEvent>;
interface OwnershipTransferredEventObject {
  from: string;
  to: string;
}

type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;
interface WithdrawnEventObject {
  to: string;
  amount: BigNumber;
}

type WithdrawnEvent = TypedEvent<
  [string, BigNumber],
  WithdrawnEventObject
>;

type WithdrawnEventFilter = TypedEventFilter<WithdrawnEvent>;
interface WrapperFulfillmentFailedEventObject {
  requestId: BigNumber;
  consumer: string;
}

type WrapperFulfillmentFailedEvent = TypedEvent<
  [BigNumber, string],
  WrapperFulfillmentFailedEventObject
>;

type WrapperFulfillmentFailedEventFilter =
  TypedEventFilter<WrapperFulfillmentFailedEvent>;

export interface VRFV2PlusWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VRFV2PlusWrapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SUBSCRIPTION_ID(overrides?: CallOverrides): Promise<[BigNumber]>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    calculateRequestPrice(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateRequestPriceNative(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    checkPaymentMode(
      extraArgs: BytesLike,
      isLinkMode: boolean,
      overrides?: CallOverrides
    ): Promise<[void]>;

    disable(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    enable(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    estimateRequestPrice(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      _requestGasPriceWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    estimateRequestPriceNative(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      _requestGasPriceWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getConfig(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        string,
        number
      ] & {
        fallbackWeiPerUnitLink: BigNumber;
        stalenessSeconds: number;
        fulfillmentFlatFeeNativePPM: number;
        fulfillmentFlatFeeLinkDiscountPPM: number;
        wrapperGasOverhead: number;
        coordinatorGasOverheadNative: number;
        coordinatorGasOverheadLink: number;
        coordinatorGasOverheadPerWord: number;
        wrapperNativePremiumPercentage: number;
        wrapperLinkPremiumPercentage: number;
        keyHash: string;
        maxNumWords: number;
      }
    >;

    lastRequestId(overrides?: CallOverrides): Promise<[BigNumber]>;

    link(overrides?: CallOverrides): Promise<[string]>;

    linkNativeFeed(overrides?: CallOverrides): Promise<[string]>;

    onTokenTransfer(
      _sender: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    requestRandomWordsInNative(
      _callbackGasLimit: BigNumberish,
      _requestConfirmations: BigNumberish,
      _numWords: BigNumberish,
      extraArgs: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    s_callbacks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, number, BigNumber] & {
        callbackAddress: string;
        callbackGasLimit: number;
        requestGasPrice: BigNumber;
      }
    >;

    s_configured(overrides?: CallOverrides): Promise<[boolean]>;

    s_disabled(overrides?: CallOverrides): Promise<[boolean]>;

    s_fulfillmentTxSizeBytes(overrides?: CallOverrides): Promise<[number]>;

    s_vrfCoordinator(overrides?: CallOverrides): Promise<[string]>;

    setConfig(
      _wrapperGasOverhead: BigNumberish,
      _coordinatorGasOverheadNative: BigNumberish,
      _coordinatorGasOverheadLink: BigNumberish,
      _coordinatorGasOverheadPerWord: BigNumberish,
      _coordinatorNativePremiumPercentage: BigNumberish,
      _coordinatorLinkPremiumPercentage: BigNumberish,
      _keyHash: BytesLike,
      _maxNumWords: BigNumberish,
      _stalenessSeconds: BigNumberish,
      _fallbackWeiPerUnitLink: BigNumberish,
      _fulfillmentFlatFeeNativePPM: BigNumberish,
      _fulfillmentFlatFeeLinkDiscountPPM: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setFulfillmentTxSize(
      _size: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    typeAndVersion(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      _recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawNative(
      _recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  SUBSCRIPTION_ID(overrides?: CallOverrides): Promise<BigNumber>;

  acceptOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  calculateRequestPrice(
    _callbackGasLimit: BigNumberish,
    _numWords: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateRequestPriceNative(
    _callbackGasLimit: BigNumberish,
    _numWords: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkPaymentMode(
    extraArgs: BytesLike,
    isLinkMode: boolean,
    overrides?: CallOverrides
  ): Promise<void>;

  disable(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  enable(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  estimateRequestPrice(
    _callbackGasLimit: BigNumberish,
    _numWords: BigNumberish,
    _requestGasPriceWei: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  estimateRequestPriceNative(
    _callbackGasLimit: BigNumberish,
    _numWords: BigNumberish,
    _requestGasPriceWei: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getConfig(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      string,
      number
    ] & {
      fallbackWeiPerUnitLink: BigNumber;
      stalenessSeconds: number;
      fulfillmentFlatFeeNativePPM: number;
      fulfillmentFlatFeeLinkDiscountPPM: number;
      wrapperGasOverhead: number;
      coordinatorGasOverheadNative: number;
      coordinatorGasOverheadLink: number;
      coordinatorGasOverheadPerWord: number;
      wrapperNativePremiumPercentage: number;
      wrapperLinkPremiumPercentage: number;
      keyHash: string;
      maxNumWords: number;
    }
  >;

  lastRequestId(overrides?: CallOverrides): Promise<BigNumber>;

  link(overrides?: CallOverrides): Promise<string>;

  linkNativeFeed(overrides?: CallOverrides): Promise<string>;

  onTokenTransfer(
    _sender: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  rawFulfillRandomWords(
    requestId: BigNumberish,
    randomWords: BigNumberish[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  requestRandomWordsInNative(
    _callbackGasLimit: BigNumberish,
    _requestConfirmations: BigNumberish,
    _numWords: BigNumberish,
    extraArgs: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  s_callbacks(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, number, BigNumber] & {
      callbackAddress: string;
      callbackGasLimit: number;
      requestGasPrice: BigNumber;
    }
  >;

  s_configured(overrides?: CallOverrides): Promise<boolean>;

  s_disabled(overrides?: CallOverrides): Promise<boolean>;

  s_fulfillmentTxSizeBytes(overrides?: CallOverrides): Promise<number>;

  s_vrfCoordinator(overrides?: CallOverrides): Promise<string>;

  setConfig(
    _wrapperGasOverhead: BigNumberish,
    _coordinatorGasOverheadNative: BigNumberish,
    _coordinatorGasOverheadLink: BigNumberish,
    _coordinatorGasOverheadPerWord: BigNumberish,
    _coordinatorNativePremiumPercentage: BigNumberish,
    _coordinatorLinkPremiumPercentage: BigNumberish,
    _keyHash: BytesLike,
    _maxNumWords: BigNumberish,
    _stalenessSeconds: BigNumberish,
    _fallbackWeiPerUnitLink: BigNumberish,
    _fulfillmentFlatFeeNativePPM: BigNumberish,
    _fulfillmentFlatFeeLinkDiscountPPM: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setCoordinator(
    _vrfCoordinator: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setFulfillmentTxSize(
    _size: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    to: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  typeAndVersion(overrides?: CallOverrides): Promise<string>;

  withdraw(
    _recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawNative(
    _recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    SUBSCRIPTION_ID(overrides?: CallOverrides): Promise<BigNumber>;

    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    calculateRequestPrice(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateRequestPriceNative(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkPaymentMode(
      extraArgs: BytesLike,
      isLinkMode: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    disable(overrides?: CallOverrides): Promise<void>;

    enable(overrides?: CallOverrides): Promise<void>;

    estimateRequestPrice(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      _requestGasPriceWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateRequestPriceNative(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      _requestGasPriceWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfig(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        number,
        string,
        number
      ] & {
        fallbackWeiPerUnitLink: BigNumber;
        stalenessSeconds: number;
        fulfillmentFlatFeeNativePPM: number;
        fulfillmentFlatFeeLinkDiscountPPM: number;
        wrapperGasOverhead: number;
        coordinatorGasOverheadNative: number;
        coordinatorGasOverheadLink: number;
        coordinatorGasOverheadPerWord: number;
        wrapperNativePremiumPercentage: number;
        wrapperLinkPremiumPercentage: number;
        keyHash: string;
        maxNumWords: number;
      }
    >;

    lastRequestId(overrides?: CallOverrides): Promise<BigNumber>;

    link(overrides?: CallOverrides): Promise<string>;

    linkNativeFeed(overrides?: CallOverrides): Promise<string>;

    onTokenTransfer(
      _sender: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    requestRandomWordsInNative(
      _callbackGasLimit: BigNumberish,
      _requestConfirmations: BigNumberish,
      _numWords: BigNumberish,
      extraArgs: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_callbacks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, number, BigNumber] & {
        callbackAddress: string;
        callbackGasLimit: number;
        requestGasPrice: BigNumber;
      }
    >;

    s_configured(overrides?: CallOverrides): Promise<boolean>;

    s_disabled(overrides?: CallOverrides): Promise<boolean>;

    s_fulfillmentTxSizeBytes(overrides?: CallOverrides): Promise<number>;

    s_vrfCoordinator(overrides?: CallOverrides): Promise<string>;

    setConfig(
      _wrapperGasOverhead: BigNumberish,
      _coordinatorGasOverheadNative: BigNumberish,
      _coordinatorGasOverheadLink: BigNumberish,
      _coordinatorGasOverheadPerWord: BigNumberish,
      _coordinatorNativePremiumPercentage: BigNumberish,
      _coordinatorLinkPremiumPercentage: BigNumberish,
      _keyHash: BytesLike,
      _maxNumWords: BigNumberish,
      _stalenessSeconds: BigNumberish,
      _fallbackWeiPerUnitLink: BigNumberish,
      _fulfillmentFlatFeeNativePPM: BigNumberish,
      _fulfillmentFlatFeeLinkDiscountPPM: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFulfillmentTxSize(
      _size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(to: string, overrides?: CallOverrides): Promise<void>;

    typeAndVersion(overrides?: CallOverrides): Promise<string>;

    withdraw(_recipient: string, overrides?: CallOverrides): Promise<void>;

    withdrawNative(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ConfigSet(uint32,uint32,uint32,uint16,uint8,uint8,bytes32,uint8,uint32,int256,uint32,uint32)"(
      wrapperGasOverhead?: null,
      coordinatorGasOverheadNative?: null,
      coordinatorGasOverheadLink?: null,
      coordinatorGasOverheadPerWord?: null,
      coordinatorNativePremiumPercentage?: null,
      coordinatorLinkPremiumPercentage?: null,
      keyHash?: null,
      maxNumWords?: null,
      stalenessSeconds?: null,
      fallbackWeiPerUnitLink?: null,
      fulfillmentFlatFeeNativePPM?: null,
      fulfillmentFlatFeeLinkDiscountPPM?: null
    ): ConfigSetEventFilter;
    ConfigSet(
      wrapperGasOverhead?: null,
      coordinatorGasOverheadNative?: null,
      coordinatorGasOverheadLink?: null,
      coordinatorGasOverheadPerWord?: null,
      coordinatorNativePremiumPercentage?: null,
      coordinatorLinkPremiumPercentage?: null,
      keyHash?: null,
      maxNumWords?: null,
      stalenessSeconds?: null,
      fallbackWeiPerUnitLink?: null,
      fulfillmentFlatFeeNativePPM?: null,
      fulfillmentFlatFeeLinkDiscountPPM?: null
    ): ConfigSetEventFilter;

    "CoordinatorSet(address)"(vrfCoordinator?: null): CoordinatorSetEventFilter;
    CoordinatorSet(vrfCoordinator?: null): CoordinatorSetEventFilter;

    "Disabled()"(): DisabledEventFilter;
    Disabled(): DisabledEventFilter;

    "Enabled()"(): EnabledEventFilter;
    Enabled(): EnabledEventFilter;

    "FallbackWeiPerUnitLinkUsed(uint256,int256)"(
      requestId?: null,
      fallbackWeiPerUnitLink?: null
    ): FallbackWeiPerUnitLinkUsedEventFilter;
    FallbackWeiPerUnitLinkUsed(
      requestId?: null,
      fallbackWeiPerUnitLink?: null
    ): FallbackWeiPerUnitLinkUsedEventFilter;

    "FulfillmentTxSizeSet(uint32)"(
      size?: null
    ): FulfillmentTxSizeSetEventFilter;
    FulfillmentTxSizeSet(size?: null): FulfillmentTxSizeSetEventFilter;

    "NativeWithdrawn(address,uint256)"(
      to?: string | null,
      amount?: null
    ): NativeWithdrawnEventFilter;
    NativeWithdrawn(
      to?: string | null,
      amount?: null
    ): NativeWithdrawnEventFilter;

    "OwnershipTransferRequested(address,address)"(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferRequestedEventFilter;
    OwnershipTransferRequested(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferRequestedEventFilter;

    "OwnershipTransferred(address,address)"(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      from?: string | null,
      to?: string | null
    ): OwnershipTransferredEventFilter;

    "Withdrawn(address,uint256)"(
      to?: string | null,
      amount?: null
    ): WithdrawnEventFilter;
    Withdrawn(to?: string | null, amount?: null): WithdrawnEventFilter;

    "WrapperFulfillmentFailed(uint256,address)"(
      requestId?: BigNumberish | null,
      consumer?: string | null
    ): WrapperFulfillmentFailedEventFilter;
    WrapperFulfillmentFailed(
      requestId?: BigNumberish | null,
      consumer?: string | null
    ): WrapperFulfillmentFailedEventFilter;
  };

  estimateGas: {
    SUBSCRIPTION_ID(overrides?: CallOverrides): Promise<BigNumber>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    calculateRequestPrice(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateRequestPriceNative(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkPaymentMode(
      extraArgs: BytesLike,
      isLinkMode: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    disable(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    enable(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    estimateRequestPrice(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      _requestGasPriceWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateRequestPriceNative(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      _requestGasPriceWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfig(overrides?: CallOverrides): Promise<BigNumber>;

    lastRequestId(overrides?: CallOverrides): Promise<BigNumber>;

    link(overrides?: CallOverrides): Promise<BigNumber>;

    linkNativeFeed(overrides?: CallOverrides): Promise<BigNumber>;

    onTokenTransfer(
      _sender: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    requestRandomWordsInNative(
      _callbackGasLimit: BigNumberish,
      _requestConfirmations: BigNumberish,
      _numWords: BigNumberish,
      extraArgs: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    s_callbacks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_configured(overrides?: CallOverrides): Promise<BigNumber>;

    s_disabled(overrides?: CallOverrides): Promise<BigNumber>;

    s_fulfillmentTxSizeBytes(overrides?: CallOverrides): Promise<BigNumber>;

    s_vrfCoordinator(overrides?: CallOverrides): Promise<BigNumber>;

    setConfig(
      _wrapperGasOverhead: BigNumberish,
      _coordinatorGasOverheadNative: BigNumberish,
      _coordinatorGasOverheadLink: BigNumberish,
      _coordinatorGasOverheadPerWord: BigNumberish,
      _coordinatorNativePremiumPercentage: BigNumberish,
      _coordinatorLinkPremiumPercentage: BigNumberish,
      _keyHash: BytesLike,
      _maxNumWords: BigNumberish,
      _stalenessSeconds: BigNumberish,
      _fallbackWeiPerUnitLink: BigNumberish,
      _fulfillmentFlatFeeNativePPM: BigNumberish,
      _fulfillmentFlatFeeLinkDiscountPPM: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setFulfillmentTxSize(
      _size: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    typeAndVersion(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      _recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawNative(
      _recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    SUBSCRIPTION_ID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    acceptOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    calculateRequestPrice(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateRequestPriceNative(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkPaymentMode(
      extraArgs: BytesLike,
      isLinkMode: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    disable(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    enable(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    estimateRequestPrice(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      _requestGasPriceWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estimateRequestPriceNative(
      _callbackGasLimit: BigNumberish,
      _numWords: BigNumberish,
      _requestGasPriceWei: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastRequestId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    link(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    linkNativeFeed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onTokenTransfer(
      _sender: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rawFulfillRandomWords(
      requestId: BigNumberish,
      randomWords: BigNumberish[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requestRandomWordsInNative(
      _callbackGasLimit: BigNumberish,
      _requestConfirmations: BigNumberish,
      _numWords: BigNumberish,
      extraArgs: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    s_callbacks(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_configured(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    s_disabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    s_fulfillmentTxSizeBytes(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_vrfCoordinator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setConfig(
      _wrapperGasOverhead: BigNumberish,
      _coordinatorGasOverheadNative: BigNumberish,
      _coordinatorGasOverheadLink: BigNumberish,
      _coordinatorGasOverheadPerWord: BigNumberish,
      _coordinatorNativePremiumPercentage: BigNumberish,
      _coordinatorLinkPremiumPercentage: BigNumberish,
      _keyHash: BytesLike,
      _maxNumWords: BigNumberish,
      _stalenessSeconds: BigNumberish,
      _fallbackWeiPerUnitLink: BigNumberish,
      _fulfillmentFlatFeeNativePPM: BigNumberish,
      _fulfillmentFlatFeeLinkDiscountPPM: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setCoordinator(
      _vrfCoordinator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setFulfillmentTxSize(
      _size: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      to: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    typeAndVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      _recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawNative(
      _recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
