// @ts-nocheck
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { IFareAA, IFareAAInterface } from '../IFareAA'

const _abi = [
  {
    inputs: [],
    name: 'ArrayLengthsMismatch',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidContract',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidContractForFundOwner',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidSubmitterForFundOwner',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidUsdcAddress',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'fundOwnerAddress',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address[]',
        name: 'contractAddresses',
        type: 'address[]',
      },
      {
        indexed: false,
        internalType: 'bool[]',
        name: 'isAlloweds',
        type: 'bool[]',
      },
    ],
    name: 'AllowedContractsSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'fundOwnerAddress',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'submitterAddress',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'isAllowed',
        type: 'bool',
      },
    ],
    name: 'AllowedSubmitterSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newRiskFactor',
        type: 'uint256',
      },
    ],
    name: 'RiskFactorSet',
    type: 'event',
  },
  {
    inputs: [],
    name: 'MINTER_ROLE',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'submitterAddress',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'fundOwnerAddress',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'collectAmount',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'feeAmount',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: 'receiverAddress',
        type: 'address',
      },
    ],
    name: 'batchChargeTrialAndFeeUsdc',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'submitterAddress',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'fundOwnerAddress',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: 'receiverAddress',
        type: 'address',
      },
    ],
    name: 'chargeFeeUsdc',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'submitterAddress',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'fundOwnerAddress',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'chargeTrialUsdc',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'contractAddress',
        type: 'address',
      },
    ],
    name: 'isMinterContract',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'potentialProfitAmount',
        type: 'uint256',
      },
    ],
    name: 'isProfitValid',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'contractAddress',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'fundOwnerAddress',
        type: 'address',
      },
    ],
    name: 'isValidContractForFundOwner',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'submitterAddress',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'fundOwnerAddress',
        type: 'address',
      },
    ],
    name: 'isValidSubmitterForFundOwner',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'fundOwnerAddress',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'payoutUsdc',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'riskFactor',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address[]',
        name: 'contractAddresses',
        type: 'address[]',
      },
      {
        internalType: 'bool[]',
        name: 'isAlloweds',
        type: 'bool[]',
      },
    ],
    name: 'setAllowedContracts',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'submitterAddress',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: 'isAllowed',
        type: 'bool',
      },
    ],
    name: 'setAllowedSubmitter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_riskFactor',
        type: 'uint256',
      },
    ],
    name: 'setRiskFactor',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usdcAddress',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export class IFareAA__factory {
  static readonly abi = _abi
  static createInterface(): IFareAAInterface {
    return new utils.Interface(_abi) as IFareAAInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IFareAA {
    return new Contract(address, _abi, signerOrProvider) as IFareAA
  }
}
